<?php

namespace Database\Seeders;

use App\Models\CodigoComplejidad;
use App\Models\Dureza;
use App\Models\FactorPremio;
use App\Models\FactorPremioUsuario;
use App\Models\ImpresoraFiscal;
use App\Models\ItemOrdenTrabajo;
use App\Models\ItemPremio;
use App\Models\Material;
use App\Models\MedioEnfriamiento;
use App\Models\OrdenTrabajo;
use App\Models\PlantillaCarga;
use App\Models\Premio;
use App\Models\Programacion;
use App\Models\PuntoDeVenta;
use App\Models\SecuenciaPtoVenta;
use App\Models\TipoCbte;
use App\Models\TipoProgramacion;
use App\Models\Tratamiento;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        ImpresoraFiscal::create([
            'Nombre' => 'EPSON Pr Fiscal PLAYA',
            'Modelo' => 'EPSON TMU220AF',
            'PuertoCOM' => '0',
            'VelocidadPrEpson' => '3',
            'TipoProtocoloPrEpson' => '0',
            'FechaUltimoCierreZ' => '2017-05-10 14:00:00',
            'PuertoComOcxIFEpson' => '1',
            'VelocidadOcxIFEpson' => '9600',
        ]);

        PuntoDeVenta::create([
            'Nombre' => '1 - DURMETAL',
            'Numero' => '1',
            'Tipo' => 'MANUAL',   
            'NotaCreditoComparteTalonario' => '0',
            'NotaDebitoComparteTalonario' => '0',
            'IdTipoRemitoVentaPorDefecto' => '0',
            'IdImpresoraFiscal' => '1',
            'UtilizarDomicilioConfiguracionGlobal' => '1',
            'DomicilioEmpresa' => null,
            'TelefonoEmpresa' => null,
            'LocalidadEmpresa' => null,
            'ProvinciaEmpresa' => null,
            'CodigoSucursal' => 01,
            'FechaCreacion' => null,
            'CreadoPor' => '1',
            'FechaActualizacion' => null,
            'ActualizadoPor' => '1',
            'Activo' => '1',
        ]);

        PuntoDeVenta::create([
            'Nombre' => '5 - AFIP WS',
            'Numero' => '5',
            'Tipo' => 'ELECTRONICO',   
            'NotaCreditoComparteTalonario' => '0',
            'NotaDebitoComparteTalonario' => '0',
            'IdTipoRemitoVentaPorDefecto' => '0',
            'IdImpresoraFiscal' => '1',
            'UtilizarDomicilioConfiguracionGlobal' => '1',
            'DomicilioEmpresa' => null,
            'TelefonoEmpresa' => null,
            'LocalidadEmpresa' => null,
            'ProvinciaEmpresa' => null,
            'CodigoSucursal' => null,
            'FechaCreacion' => null,
            'CreadoPor' => '1',
            'FechaActualizacion' => null,
            'ActualizadoPor' => '1',
            'Activo' => '1',
        ]);

        TipoCbte::create([
            'Nombre' => 'FC A',
        ]);

        SecuenciaPtoVenta::create([
            'IdPtoVenta' => '1',
            'IdTipoCbte' => '1',
            'Secuencia' => '1',
            'ImprimirNumero' => '0',
            'ImprimirNumeroCompleto' => '0',
            'ImprimirTipoCbte' => '0',
            'NombreTipoCbte' => null,
        ]);

        $durezas = [
            ['id' => 1, 'Nombre' => 'HB', 'Descripcion' => 'DUREZA BRINELL 3000/10', 'Predeterminado' => 0],
            ['id' => 2, 'Nombre' => 'HRB', 'Descripcion' => 'ROCKWELL B', 'Predeterminado' => 0],
            ['id' => 3, 'Nombre' => 'HRC', 'Descripcion' => 'DUREZA ROCKWELL C', 'Predeterminado' => 1],
            ['id' => 4, 'Nombre' => 'HRF', 'Descripcion' => 'BOL.1/16 - 60Kg', 'Predeterminado' => 0],
            ['id' => 5, 'Nombre' => 'HV', 'Descripcion' => 'Dureza Vickers', 'Predeterminado' => 0],
            ['id' => 6, 'Nombre' => 'KMM2', 'Descripcion' => 'RESIST. EN Kg/mm2', 'Predeterminado' => 0],
            ['id' => 7, 'Nombre' => 'KSI', 'Descripcion' => 'Resistencia Ksi', 'Predeterminado' => 0],
            ['id' => 8, 'Nombre' => 'MPA', 'Descripcion' => 'Mega Pascal', 'Predeterminado' => 0],
            ['id' => 9, 'Nombre' => 'NESP', 'Descripcion' => 'NO ESPECIFICADO', 'Predeterminado' => 0],
            ['id' => 10, 'Nombre' => 'NMM2', 'Descripcion' => 'Newton/mm²', 'Predeterminado' => 0],
            ['id' => 12, 'Nombre' => 'SHOR', 'Descripcion' => 'DUREZA SHORE', 'Predeterminado' => 0],
            ['id' => 18, 'Nombre' => 'DSH', 'Descripcion' => 'DSH (MIGRACION)', 'Predeterminado' => 0],
            ['id' => 19, 'Nombre' => 'NOES', 'Descripcion' => 'NOES', 'Predeterminado' => 0],
            ['id' => 20, 'Nombre' => 'NO APLICA', 'Descripcion' => 'NO APLICA', 'Predeterminado' => 0],
            ['id' => 21, 'Nombre' => 'PSI', 'Descripcion' => 'RESISTENCIA PSI', 'Predeterminado' => 0],
        ];

        Dureza::insert($durezas);

        $materiales = [
            ['id' => 1, 'Nombre' => '16CrMn5', 'Descripcion' => 'AC.CEMENTACION', 'Predeterminado' => 0],
            ['id' => 2, 'Nombre' => '16MnCr5', 'Descripcion' => 'SIMIL 1010', 'Predeterminado' => 0],
            ['id' => 3, 'Nombre' => '17CrNiMo', 'Descripcion' => '17CRNIMO6(CEM.SIMIL 8620)', 'Predeterminado' => 0],
            ['id' => 4, 'Nombre' => '32CVD13', 'Descripcion' => 'AC.CR,V,MO P/NITRURACIóN', 'Predeterminado' => 0],
            ['id' => 5, 'Nombre' => '40CAD612', 'Descripcion' => 'ACERO NITRUR.(890º/930º)', 'Predeterminado' => 0],
            ['id' => 6, 'Nombre' => '42CrMo4V', 'Descripcion' => 'ACERO ALEADO SIMIL 4140', 'Predeterminado' => 0],
            ['id' => 7, 'Nombre' => 'A-297 HH', 'Descripcion' => 'INOX.AUST 25-12', 'Predeterminado' => 0],
            ['id' => 8, 'Nombre' => 'A-532IIC', 'Descripcion' => 'FUND.BLANCA CR 15 MO 2.3', 'Predeterminado' => 0],
            ['id' => 9, 'Nombre' => 'A-536 80', 'Descripcion' => 'FUNDICION NODULAR', 'Predeterminado' => 0],
            ['id' => 10, 'Nombre' => 'A.174PH', 'Descripcion' => 'AC.INOX.END.PRECIPITACIÓN', 'Predeterminado' => 0],
            ['id' => 11, 'Nombre' => 'A.536-70', 'Descripcion' => 'FUND.NODULAR', 'Predeterminado' => 0],
            ['id' => 12, 'Nombre' => 'A.A 148', 'Descripcion' => 'AC.FUND.ALTA RESIST.', 'Predeterminado' => 0],
            ['id' => 13, 'Nombre' => 'A.A-27', 'Descripcion' => 'AC.CEMENTACION', 'Predeterminado' => 0],
            ['id' => 14, 'Nombre' => 'A.A-339', 'Descripcion' => 'FUND. GRIS DESACT', 'Predeterminado' => 0],
            ['id' => 15, 'Nombre' => 'A.A-48', 'Descripcion' => 'FUND.GRIS', 'Predeterminado' => 0],
            ['id' => 16, 'Nombre' => 'A.A-516', 'Descripcion' => 'AC.CONSTRUCCION', 'Predeterminado' => 0],
            ['id' => 17, 'Nombre' => 'A.A128-A', 'Descripcion' => 'A.AUSTENITICO AL MANGANES', 'Predeterminado' => 0],
            ['id' => 18, 'Nombre' => 'A.A128B4', 'Descripcion' => 'AC.AUSTENITICO AL MANGANE', 'Predeterminado' => 0],
            ['id' => 19, 'Nombre' => 'A.A296', 'Descripcion' => 'MATERIAL FUNDIDO', 'Predeterminado' => 0],
            ['id' => 20, 'Nombre' => 'A.A297', 'Descripcion' => 'INOXIDABLE FUNDIDO', 'Predeterminado' => 0],
            ['id' => 21, 'Nombre' => 'A.A53282', 'Descripcion' => 'ASTM A532-82 CLASE II T.C', 'Predeterminado' => 0],
            ['id' => 22, 'Nombre' => 'A.RAPIDO', 'Descripcion' => 'AC.P/HERRAMIENTAS', 'Predeterminado' => 0],
            ['id' => 23, 'Nombre' => 'AC./BORO', 'Descripcion' => 'AC.PARA CUCHILLAS', 'Predeterminado' => 0],
            ['id' => 24, 'Nombre' => 'AC.INOX', 'Descripcion' => 'AC.INOX.VARIOS', 'Predeterminado' => 0],
            ['id' => 25, 'Nombre' => 'AC.PLATA', 'Descripcion' => 'AC. RECTIFICADO', 'Predeterminado' => 0],
            ['id' => 26, 'Nombre' => 'AISI 302', 'Descripcion' => 'ACERO INOX.AUSTEN.', 'Predeterminado' => 0],
            ['id' => 27, 'Nombre' => 'AISI 303', 'Descripcion' => 'AC.INOX.AUTENITICO', 'Predeterminado' => 0],
            ['id' => 28, 'Nombre' => 'AISI 304', 'Descripcion' => 'ACERO INOX.AUSTEN.', 'Predeterminado' => 0],
            ['id' => 29, 'Nombre' => 'AISI 309', 'Descripcion' => 'AC.INOXIDABLE AUSTENITICO', 'Predeterminado' => 0],
            ['id' => 30, 'Nombre' => 'AISI 316', 'Descripcion' => 'ACERO INOX.AUSTENIT.', 'Predeterminado' => 0],
            ['id' => 31, 'Nombre' => 'AISI 410', 'Descripcion' => 'AC.INOX.', 'Predeterminado' => 0],
            ['id' => 32, 'Nombre' => 'AISI 416', 'Descripcion' => 'AC.INOXIDABLE', 'Predeterminado' => 0],
            ['id' => 33, 'Nombre' => 'AISI 420', 'Descripcion' => 'AC.INOX.', 'Predeterminado' => 0],
            ['id' => 34, 'Nombre' => 'AISI 430', 'Descripcion' => 'AC.INOXIDABLE', 'Predeterminado' => 0],
            ['id' => 35, 'Nombre' => 'AISI 431', 'Descripcion' => 'AC.INOX.MARTENSITICO', 'Predeterminado' => 0],
            ['id' => 36, 'Nombre' => 'AISI 440', 'Descripcion' => 'INOXIDABLE FUND.MARTENSIT', 'Predeterminado' => 0],
            ['id' => 37, 'Nombre' => 'AISI D1', 'Descripcion' => 'AC.INDEF.12% CR-1% C', 'Predeterminado' => 0],
            ['id' => 38, 'Nombre' => 'AISI D2', 'Descripcion' => 'AC.INDEF.TEMP.AIRE', 'Predeterminado' => 0],
            ['id' => 39, 'Nombre' => 'AISI D3', 'Descripcion' => 'AC.INDEF.12%CR-2.1%C', 'Predeterminado' => 0],
            ['id' => 40, 'Nombre' => 'AISI D6', 'Descripcion' => 'AC.INDEFORMABLE', 'Predeterminado' => 0],
            ['id' => 41, 'Nombre' => 'AISI H10', 'Descripcion' => 'AC.TR.CALIENTE', 'Predeterminado' => 0],
            ['id' => 42, 'Nombre' => 'AISI H11', 'Descripcion' => 'AC.TRAB.CALIENTE', 'Predeterminado' => 0],
            ['id' => 43, 'Nombre' => 'AISI H12', 'Descripcion' => 'AC.TRAB.CALIENTE', 'Predeterminado' => 0],
            ['id' => 44, 'Nombre' => 'AISI H13', 'Descripcion' => 'AC.TRAB.EN CALIENTE', 'Predeterminado' => 0],
            ['id' => 45, 'Nombre' => 'AISI H21', 'Descripcion' => 'AC.TRAB.CALIENTE', 'Predeterminado' => 0],
            ['id' => 46, 'Nombre' => 'AISI L6', 'Descripcion' => 'AC.TRABAJO EN CAL.', 'Predeterminado' => 0],
            ['id' => 47, 'Nombre' => 'AISI M2', 'Descripcion' => 'ACERO RAPIDO', 'Predeterminado' => 0],
            ['id' => 48, 'Nombre' => 'AISI O1', 'Descripcion' => 'AC.INDEF.(=VERESTA)', 'Predeterminado' => 0],
            ['id' => 49, 'Nombre' => 'AISI S1', 'Descripcion' => 'AC.RESIST.GOLPES', 'Predeterminado' => 0],
            ['id' => 50, 'Nombre' => 'AISI S7', 'Descripcion' => 'ACERO RESIST GOLPES', 'Predeterminado' => 0],
            ['id' => 51, 'Nombre' => 'AISI W1', 'Descripcion' => 'AC.TEMPLE AL AGUA', 'Predeterminado' => 0],
            ['id' => 52, 'Nombre' => 'ALCOHOL', 'Descripcion' => 'ALCOHOL ISOP', 'Predeterminado' => 0],
            ['id' => 53, 'Nombre' => 'ALCOISOP', 'Descripcion' => 'ALCOHOL ISOPROPILICO', 'Predeterminado' => 0],
            ['id' => 54, 'Nombre' => 'ALUMINIO', 'Descripcion' => 'ALEACION DE ALUMINIO', 'Predeterminado' => 0],
            ['id' => 55, 'Nombre' => 'ALVAR 14', 'Descripcion' => 'AC.TRABAJO EN CALIENTE', 'Predeterminado' => 0],
            ['id' => 56, 'Nombre' => 'AMSextra', 'Descripcion' => 'AC.P/HERRAMIENTAS', 'Predeterminado' => 0],
            ['id' => 57, 'Nombre' => 'AMUTIT', 'Descripcion' => 'ACERO TIPO AISI O1', 'Predeterminado' => 0],
            ['id' => 58, 'Nombre' => 'ARNE', 'Descripcion' => 'SIMIL O1 (UDDEHOLM)', 'Predeterminado' => 0],
            ['id' => 59, 'Nombre' => 'ASTM A36', 'Descripcion' => 'C:0.25', 'Predeterminado' => 0],
            ['id' => 60, 'Nombre' => 'ASTRALOY', 'Descripcion' => 'CHAPA FUNDIDA CON DUREZA', 'Predeterminado' => 0],
            ['id' => 61, 'Nombre' => 'AWS', 'Descripcion' => 'STYRIA-TRABAJO EN CALIENT', 'Predeterminado' => 0],
            ['id' => 62, 'Nombre' => 'BRONCE', 'Descripcion' => 'MAT. BLANDO', 'Predeterminado' => 0],
            ['id' => 63, 'Nombre' => 'C190V9CR', 'Descripcion' => 'ACERO 1.9%C;V 9%;CROMO 5%', 'Predeterminado' => 0],
            ['id' => 64, 'Nombre' => 'C240CR5V', 'Descripcion' => 'FUND.BCA C2.45 CR.5 V:9', 'Predeterminado' => 0],
            ['id' => 65, 'Nombre' => 'C28/C32', 'Descripcion' => 'AC.AL CARBONO EQ SAE 1030', 'Predeterminado' => 0],
            ['id' => 66, 'Nombre' => 'CA-15', 'Descripcion' => 'EQUIV.410 FUNDIDO', 'Predeterminado' => 0],
            ['id' => 67, 'Nombre' => 'CAD 6-12', 'Descripcion' => 'AC.THYSSEN(SIMIL S1)', 'Predeterminado' => 0],
            ['id' => 68, 'Nombre' => 'CALMAX', 'Descripcion' => 'SIMIL D6 - UDDEHOLM', 'Predeterminado' => 0],
            ['id' => 69, 'Nombre' => 'CD4MCu', 'Descripcion' => 'ACERO INOX. END. POR PREC', 'Predeterminado' => 0],
            ['id' => 70, 'Nombre' => 'CNK2', 'Descripcion' => 'ACERO CR-NI', 'Predeterminado' => 0],
            ['id' => 71, 'Nombre' => 'COBRE', 'Descripcion' => 'MAT. BLANDO', 'Predeterminado' => 0],
            ['id' => 72, 'Nombre' => 'CR.MO.4', 'Descripcion' => 'EQUIV.SAE 4140', 'Predeterminado' => 0],
            ['id' => 73, 'Nombre' => 'CROD2436', 'Descripcion' => 'AC.INDEF.SVERKER3 (D6)', 'Predeterminado' => 0],
            ['id' => 74, 'Nombre' => 'CU-NI', 'Descripcion' => 'ALEAC.CU-NI', 'Predeterminado' => 0],
            ['id' => 75, 'Nombre' => 'Cr12MoV', 'Descripcion' => 'AC.SIMIL AISI D2', 'Predeterminado' => 0],
            ['id' => 76, 'Nombre' => 'CrESP.B', 'Descripcion' => 'AC.INDEF.P/HERRAM.', 'Predeterminado' => 0],
            ['id' => 77, 'Nombre' => 'MATDESC', 'Descripcion' => 'MAT.DESCONOCIDO', 'Predeterminado' => 0],
            ['id' => 78, 'Nombre' => 'DW2', 'Descripcion' => 'ACERO ALEADO AISI S1', 'Predeterminado' => 0],
            ['id' => 79, 'Nombre' => 'E 110', 'Descripcion' => 'AC.CEMENTACION', 'Predeterminado' => 0],
            ['id' => 80, 'Nombre' => 'E 200', 'Descripcion' => 'AC. CEMENTACION', 'Predeterminado' => 0],
            ['id' => 81, 'Nombre' => 'E 38K', 'Descripcion' => 'AC.PARA CUCHILLAS', 'Predeterminado' => 0],
            ['id' => 82, 'Nombre' => 'E.T.D.', 'Descripcion' => 'EXTRA TENAZ DURO', 'Predeterminado' => 0],
            ['id' => 83, 'Nombre' => 'EH 500', 'Descripcion' => 'CHAPA ANTIDESGASTE', 'Predeterminado' => 0],
            ['id' => 84, 'Nombre' => 'EHARD500', 'Descripcion' => 'CHAPA PARA BLINDAJE', 'Predeterminado' => 0],
            ['id' => 85, 'Nombre' => 'ESP.K', 'Descripcion' => 'AC.INDEF.', 'Predeterminado' => 0],
            ['id' => 86, 'Nombre' => 'F 24', 'Descripcion' => 'ACERO CONSTRUCCION 1010', 'Predeterminado' => 0],
            ['id' => 87, 'Nombre' => 'F-36', 'Descripcion' => 'ACERO CONSTRUCCION 1036', 'Predeterminado' => 0],
            ['id' => 88, 'Nombre' => 'F.GRIS', 'Descripcion' => 'FUNDICION GRIS', 'Predeterminado' => 0],
            ['id' => 89, 'Nombre' => 'F.R.V', 'Descripcion' => 'C:1.9 CR:20.5 W:1.4 V:0.7', 'Predeterminado' => 0],
            ['id' => 90, 'Nombre' => 'FUND.BCA', 'Descripcion' => 'FUNDICIÓN BLANCA', 'Predeterminado' => 0],
            ['id' => 91, 'Nombre' => 'FUND.NOD', 'Descripcion' => 'FUNDICION', 'Predeterminado' => 0],
            ['id' => 92, 'Nombre' => 'G.S.W', 'Descripcion' => 'C:0.7 CR:14.0 NI:1.2', 'Predeterminado' => 0],
            ['id' => 93, 'Nombre' => 'GG-21', 'Descripcion' => 'FUNDICION GRIS', 'Predeterminado' => 0],
            ['id' => 94, 'Nombre' => 'GR.AM500', 'Descripcion' => 'IRAM 500-7026', 'Predeterminado' => 0],
            ['id' => 95, 'Nombre' => 'GS 60', 'Descripcion' => 'C:0.40CR:0.4 NI:0.5 MO:.2', 'Predeterminado' => 0],
            ['id' => 96, 'Nombre' => 'GS-36Mn5', 'Descripcion' => 'ACERO ALEADO', 'Predeterminado' => 0],
            ['id' => 97, 'Nombre' => 'GS-700', 'Descripcion' => 'FUNDICION', 'Predeterminado' => 0],
            ['id' => 98, 'Nombre' => 'GX180CrW', 'Descripcion' => 'AC.INOXIDABLE', 'Predeterminado' => 0],
            ['id' => 99, 'Nombre' => 'HADFIELD', 'Descripcion' => 'AC.AUSTENIT.AL MANGANESO', 'Predeterminado' => 0],
            ['id' => 100, 'Nombre' => 'IRAM 500', 'Descripcion' => 'IRAM 500-7026', 'Predeterminado' => 0],
            ['id' => 101, 'Nombre' => 'ISOP', 'Descripcion' => 'ALCOHOL ISOPROPILICO', 'Predeterminado' => 0],
            ['id' => 102, 'Nombre' => 'J 431', 'Descripcion' => 'FUNDICION GRIS/850ºACEITE', 'Predeterminado' => 0],
            ['id' => 103, 'Nombre' => 'J 435', 'Descripcion' => 'ACERO FUNDIDO ALEADO', 'Predeterminado' => 0],
            ['id' => 104, 'Nombre' => 'K 100', 'Descripcion' => 'AC. INDEFORMABLE', 'Predeterminado' => 0],
            ['id' => 105, 'Nombre' => 'K 110', 'Descripcion' => 'AC.INDEFORMABLE', 'Predeterminado' => 0],
            ['id' => 106, 'Nombre' => 'K 190', 'Descripcion' => 'AC.TRAB.EN FRIO', 'Predeterminado' => 0],
            ['id' => 107, 'Nombre' => 'K 245', 'Descripcion' => 'AC.HERRAMIENTAS', 'Predeterminado' => 0],
            ['id' => 108, 'Nombre' => 'K 300', 'Descripcion' => 'ACERO PARA T.FRIO', 'Predeterminado' => 0],
            ['id' => 109, 'Nombre' => 'K 329', 'Descripcion' => 'AC.P/HERRAMIENTA TRAB.FRI', 'Predeterminado' => 0],
            ['id' => 110, 'Nombre' => 'K 340', 'Descripcion' => 'AC.TRABAJO EN FRIO', 'Predeterminado' => 0],
            ['id' => 111, 'Nombre' => 'K 390', 'Descripcion' => 'AC.INDEFORMABLE SIM.K340', 'Predeterminado' => 0],
            ['id' => 112, 'Nombre' => 'K 455', 'Descripcion' => 'AC.CORTE EN FRIO', 'Predeterminado' => 0],
            ['id' => 113, 'Nombre' => 'K 460', 'Descripcion' => 'AC.INDEFORMABLE', 'Predeterminado' => 0],
            ['id' => 114, 'Nombre' => 'K 600', 'Descripcion' => 'AC.TRABAJO EN FRIO', 'Predeterminado' => 0],
            ['id' => 115, 'Nombre' => 'KSS', 'Descripcion' => 'AC. ESPECIAL', 'Predeterminado' => 0],
            ['id' => 116, 'Nombre' => 'M 200', 'Descripcion' => 'ACERO ALEADO', 'Predeterminado' => 0],
            ['id' => 117, 'Nombre' => 'M 238', 'Descripcion' => 'ACERO ALEADO P/PLASTICOS', 'Predeterminado' => 0],
            ['id' => 118, 'Nombre' => 'M2', 'Descripcion' => 'AC.HERRAMIENTA', 'Predeterminado' => 0],
            ['id' => 119, 'Nombre' => 'MEEHANIT', 'Descripcion' => 'FUNDICION ESPECIAL', 'Predeterminado' => 0],
            ['id' => 120, 'Nombre' => 'MO 20', 'Descripcion' => 'AC.RAPIDO P/HERRAMIENTAS', 'Predeterminado' => 0],
            ['id' => 121, 'Nombre' => 'N 695', 'Descripcion' => 'AC.INOX.EQUIV.AISI 440', 'Predeterminado' => 0],
            ['id' => 123, 'Nombre' => 'NIT.34', 'Descripcion' => 'ACERO CONSTRUCCION', 'Predeterminado' => 0],
            ['id' => 124, 'Nombre' => 'NIT.40', 'Descripcion' => 'AC.NITRURACION', 'Predeterminado' => 0],
            ['id' => 125, 'Nombre' => 'NO DETER', 'Descripcion' => 'MATERIAL DESCONOCIDO', 'Predeterminado' => 0],
            ['id' => 126, 'Nombre' => 'Ni-Res.2', 'Descripcion' => 'F.NOD AUSTENITICA A-439', 'Predeterminado' => 0],
            ['id' => 127, 'Nombre' => 'ORVAR 2M', 'Descripcion' => 'SIMIL H13', 'Predeterminado' => 0],
            ['id' => 128, 'Nombre' => 'OVAR 2M', 'Descripcion' => 'SIMIL H13 (UDDEHOLM)', 'Predeterminado' => 0],
            ['id' => 129, 'Nombre' => 'P 20', 'Descripcion' => 'ACERO AL NIQUEL (4340)', 'Predeterminado' => 0],
            ['id' => 130, 'Nombre' => 'P 200', 'Descripcion' => 'DESCONOCIDO', 'Predeterminado' => 0],
            ['id' => 131, 'Nombre' => 'POLD2002', 'Descripcion' => 'ACERO RAPIDO', 'Predeterminado' => 0],
            ['id' => 132, 'Nombre' => 'QRO-90', 'Descripcion' => 'SIMIL H13 (UDDEHOLM)', 'Predeterminado' => 0],
            ['id' => 133, 'Nombre' => 'REFRACT.', 'Descripcion' => 'MATERIAL MAMPOSTERIA', 'Predeterminado' => 0],
            ['id' => 134, 'Nombre' => 'S 600', 'Descripcion' => 'AC.HERRAMIENTAS', 'Predeterminado' => 0],
            ['id' => 135, 'Nombre' => 'SAE 1010', 'Descripcion' => 'AC.CEMENT.', 'Predeterminado' => 0],
            ['id' => 136, 'Nombre' => 'SAE 1015', 'Descripcion' => 'AC.CEMENTACION', 'Predeterminado' => 0],
            ['id' => 137, 'Nombre' => 'SAE 1020', 'Descripcion' => 'ACERO CEMENTACION', 'Predeterminado' => 0],
            ['id' => 138, 'Nombre' => 'SAE 1025', 'Descripcion' => 'ACERO CONSTRUCCION', 'Predeterminado' => 0],
            ['id' => 139, 'Nombre' => 'SAE 1030', 'Descripcion' => 'AC.CONSTRUCCION', 'Predeterminado' => 0],
            ['id' => 140, 'Nombre' => 'SAE 1038', 'Descripcion' => 'AC.CONSTRUCCION AL C', 'Predeterminado' => 0],
            ['id' => 141, 'Nombre' => 'SAE 1040', 'Descripcion' => 'AC.CONSTRUCCION', 'Predeterminado' => 0],
            ['id' => 142, 'Nombre' => 'SAE 1045', 'Descripcion' => 'AC.CONSTRUCCION', 'Predeterminado' => 0],
            ['id' => 143, 'Nombre' => 'SAE 1050', 'Descripcion' => 'AC.CONSTRUCCION', 'Predeterminado' => 0],
            ['id' => 144, 'Nombre' => 'SAE 1060', 'Descripcion' => 'AC.CONSTRUCCION', 'Predeterminado' => 0],
            ['id' => 145, 'Nombre' => 'SAE 1070', 'Descripcion' => 'AC. CONSTRUCCION', 'Predeterminado' => 0],
            ['id' => 146, 'Nombre' => 'SAE 1080', 'Descripcion' => 'ACERO CONSTRUCCION', 'Predeterminado' => 0],
            ['id' => 147, 'Nombre' => 'SAE 1095', 'Descripcion' => 'AC.CONSTRUCCION', 'Predeterminado' => 0],
            ['id' => 148, 'Nombre' => 'SAE 1112', 'Descripcion' => 'AC.CONSTRUCCION(PB)', 'Predeterminado' => 0],
            ['id' => 149, 'Nombre' => 'SAE 1212', 'Descripcion' => 'AC.CONSTRUCCION(PB)', 'Predeterminado' => 0],
            ['id' => 150, 'Nombre' => 'SAE 1524', 'Descripcion' => 'AC.CARBONO ALTO MANG', 'Predeterminado' => 0],
            ['id' => 151, 'Nombre' => 'SAE 309', 'Descripcion' => 'ALEACION ALUMINIO', 'Predeterminado' => 0],
            ['id' => 152, 'Nombre' => 'SAE 3115', 'Descripcion' => 'AC. CEMENTACION', 'Predeterminado' => 0],
            ['id' => 153, 'Nombre' => 'SAE 3135', 'Descripcion' => 'AC.ALEADO CONSTRUC.', 'Predeterminado' => 0],
            ['id' => 154, 'Nombre' => 'SAE 3310', 'Descripcion' => 'AC.CEMENTACION', 'Predeterminado' => 0],
            ['id' => 155, 'Nombre' => 'SAE 3312', 'Descripcion' => 'AC.CEMENTACION', 'Predeterminado' => 0],
            ['id' => 156, 'Nombre' => 'SAE 3315', 'Descripcion' => 'AC.CEMENTACION', 'Predeterminado' => 0],
            ['id' => 157, 'Nombre' => 'SAE 3335', 'Descripcion' => 'AC.CONSTR.CR-NI', 'Predeterminado' => 0],
            ['id' => 158, 'Nombre' => 'SAE 3340', 'Descripcion' => 'ACERO CONSTR.ALEADO', 'Predeterminado' => 0],
            ['id' => 159, 'Nombre' => 'SAE 4130', 'Descripcion' => 'AC.CONSTRUCCION', 'Predeterminado' => 0],
            ['id' => 160, 'Nombre' => 'SAE 4140', 'Descripcion' => 'AC.CONSTRUCCION', 'Predeterminado' => 1],
            ['id' => 161, 'Nombre' => 'SAE 4150', 'Descripcion' => 'AC.CONSTRUCCION', 'Predeterminado' => 0],
            ['id' => 162, 'Nombre' => 'SAE 430A', 'Descripcion' => 'BRONCE AL ALUMINIO', 'Predeterminado' => 0],
            ['id' => 163, 'Nombre' => 'SAE 430B', 'Descripcion' => 'ALEACION DE BRONCE', 'Predeterminado' => 0],
            ['id' => 164, 'Nombre' => 'SAE 4320', 'Descripcion' => 'AC.CEMENTACION', 'Predeterminado' => 0],
            ['id' => 165, 'Nombre' => 'SAE 4340', 'Descripcion' => 'AC.CONSTRUCCION', 'Predeterminado' => 0],
            ['id' => 166, 'Nombre' => 'SAE 4350', 'Descripcion' => 'ACERO ALEADO FUNDIDO', 'Predeterminado' => 0],
            ['id' => 167, 'Nombre' => 'SAE 5115', 'Descripcion' => 'ACERO ALEADO', 'Predeterminado' => 0],
            ['id' => 168, 'Nombre' => 'SAE 5160', 'Descripcion' => 'AC.CONSTR.P/ELAST.', 'Predeterminado' => 0],
            ['id' => 169, 'Nombre' => 'SAE 6150', 'Descripcion' => 'CROMO-VANADIO PARA TEMLE', 'Predeterminado' => 0],
            ['id' => 170, 'Nombre' => 'SAE 64', 'Descripcion' => 'ALEACION DE BRONCE', 'Predeterminado' => 0],
            ['id' => 171, 'Nombre' => 'SAE 8620', 'Descripcion' => 'AC.CEMENT.ALEADO', 'Predeterminado' => 0],
            ['id' => 172, 'Nombre' => 'SAE 8640', 'Descripcion' => 'AC.CONSTRUCCION', 'Predeterminado' => 0],
            ['id' => 173, 'Nombre' => 'SAE 8822', 'Descripcion' => 'ACERO ALEADO', 'Predeterminado' => 0],
            ['id' => 174, 'Nombre' => 'SAE 9260', 'Descripcion' => 'AC.CONSTR.P/ELAST.', 'Predeterminado' => 0],
            ['id' => 175, 'Nombre' => 'SAE M2', 'Descripcion' => 'ACERO RAPIDO', 'Predeterminado' => 0],
            ['id' => 176, 'Nombre' => 'SAE12L14', 'Descripcion' => 'AC.CONSTRUCCION(PB)', 'Predeterminado' => 0],
            ['id' => 177, 'Nombre' => 'SAE15B30', 'Descripcion' => 'AC.0,30 C;1.20-1.5 MN', 'Predeterminado' => 0],
            ['id' => 178, 'Nombre' => 'SAE51100', 'Descripcion' => 'SIMIL 52100', 'Predeterminado' => 0],
            ['id' => 179, 'Nombre' => 'SAE52100', 'Descripcion' => 'AC. ESPECIALES', 'Predeterminado' => 0],
            ['id' => 180, 'Nombre' => 'ST 52', 'Descripcion' => 'AC.FUND.SIMIL 1030-1035', 'Predeterminado' => 0],
            ['id' => 181, 'Nombre' => 'SVERKE21', 'Descripcion' => 'ACERO EQUIV. AISI D2', 'Predeterminado' => 0],
            ['id' => 182, 'Nombre' => 'SWS', 'Descripcion' => 'AC.INDEF.P/HERRAM.', 'Predeterminado' => 0],
            ['id' => 183, 'Nombre' => 'T-1A', 'Descripcion' => 'C:.25 CR,NI,MO,CU', 'Predeterminado' => 0],
            ['id' => 184, 'Nombre' => 'TENAX N', 'Descripcion' => 'AC.RESIST.A GOLPES', 'Predeterminado' => 0],
            ['id' => 185, 'Nombre' => 'TENIT KL', 'Descripcion' => 'AC. HERRAMIENTAS (STYRIA)', 'Predeterminado' => 0],
            ['id' => 186, 'Nombre' => 'TENIT W', 'Descripcion' => 'ACERO PARA GOLPES STYRIA', 'Predeterminado' => 0],
            ['id' => 187, 'Nombre' => 'THY.2344', 'Descripcion' => 'AC.TIPO AISI H13', 'Predeterminado' => 0],
            ['id' => 188, 'Nombre' => 'THY.2367', 'Descripcion' => 'TRAB.CALIENTE', 'Predeterminado' => 0],
            ['id' => 189, 'Nombre' => 'THY.2379', 'Descripcion' => 'ACERO THYSSEN (D2)', 'Predeterminado' => 0],
            ['id' => 190, 'Nombre' => 'THY.2436', 'Descripcion' => 'AC.INDEF.EQUIV.AISI D6', 'Predeterminado' => 0],
            ['id' => 191, 'Nombre' => 'THY.2510', 'Descripcion' => 'AC.TRABAJO EN FRIO', 'Predeterminado' => 0],
            ['id' => 192, 'Nombre' => 'THY.2550', 'Descripcion' => 'AC.RESIST.AL IMPACTO', 'Predeterminado' => 0],
            ['id' => 193, 'Nombre' => 'THY.2714', 'Descripcion' => 'SIMIL AISI L6', 'Predeterminado' => 0],
            ['id' => 194, 'Nombre' => 'THY.2738', 'Descripcion' => 'AC.PARA MOLDES D PLASTICO', 'Predeterminado' => 0],
            ['id' => 195, 'Nombre' => 'THY.2767', 'Descripcion' => 'AC.TRABAJO EN FRIO', 'Predeterminado' => 0],
            ['id' => 196, 'Nombre' => 'THY.2990', 'Descripcion' => 'AC.TRABAJO CALIENTE (H13)', 'Predeterminado' => 0],
            ['id' => 197, 'Nombre' => 'THY.3343', 'Descripcion' => 'SIMIL M2 (AC.RAPIDO)', 'Predeterminado' => 0],
            ['id' => 198, 'Nombre' => 'THY.8550', 'Descripcion' => 'AC.NITRURACION', 'Predeterminado' => 0],
            ['id' => 199, 'Nombre' => 'THY.TSP4', 'Descripcion' => 'ACERO RAPIDO', 'Predeterminado' => 0],
            ['id' => 200, 'Nombre' => 'THY40CAD', 'Descripcion' => 'ACERO NITRURACION', 'Predeterminado' => 0],
            ['id' => 201, 'Nombre' => 'TITANIO', 'Descripcion' => 'ACERO ESPECIAL', 'Predeterminado' => 0],
            ['id' => 202, 'Nombre' => 'TRANTINL', 'Descripcion' => 'INOX.AUST.SIMIL 302/303', 'Predeterminado' => 0],
            ['id' => 203, 'Nombre' => 'TRILOY', 'Descripcion' => 'SIMIL 4340 CR NI MO', 'Predeterminado' => 0],
            ['id' => 204, 'Nombre' => 'TSP4', 'Descripcion' => 'ACERO RAPIDO', 'Predeterminado' => 0],
            ['id' => 205, 'Nombre' => 'US ULTRA', 'Descripcion' => 'AC.HERRAMIENTA STYRIA', 'Predeterminado' => 0],
            ['id' => 206, 'Nombre' => 'V 155', 'Descripcion' => 'SIMIL 4340', 'Predeterminado' => 0],
            ['id' => 207, 'Nombre' => 'V 820', 'Descripcion' => 'AC.NITRURACION (BOHELER)', 'Predeterminado' => 0],
            ['id' => 208, 'Nombre' => 'VANAD.4', 'Descripcion' => 'AC.TRABAJO CAL.940º/1150º', 'Predeterminado' => 0],
            ['id' => 209, 'Nombre' => 'VERESTA', 'Descripcion' => 'ACERO INDEF.AISI O1', 'Predeterminado' => 0],
            ['id' => 210, 'Nombre' => 'VF800AT', 'Descripcion' => 'AC.TRABAJO FRIO(SIMIL D2)', 'Predeterminado' => 0],
            ['id' => 211, 'Nombre' => 'W 100', 'Descripcion' => 'AC.TRAB.CALIENTE', 'Predeterminado' => 0],
            ['id' => 212, 'Nombre' => 'W 300', 'Descripcion' => 'AC.TRAB.CALIENTE', 'Predeterminado' => 0],
            ['id' => 213, 'Nombre' => 'W 302', 'Descripcion' => 'ACERO TIPO AISI H13', 'Predeterminado' => 0],
            ['id' => 214, 'Nombre' => 'W 303', 'Descripcion' => 'AC.TRAB.CALIENTE', 'Predeterminado' => 0],
            ['id' => 215, 'Nombre' => 'W 320', 'Descripcion' => 'AC.INDEFORMABLE', 'Predeterminado' => 0],
            ['id' => 216, 'Nombre' => 'W 321', 'Descripcion' => 'AC.TRAB.CALIENTE(BOHELER)', 'Predeterminado' => 0],
            ['id' => 217, 'Nombre' => 'W 360', 'Descripcion' => 'AC.TRAB.CALIENTE', 'Predeterminado' => 0],
            ['id' => 218, 'Nombre' => 'W 400', 'Descripcion' => 'AC.TRABAJO EN CALIENTE', 'Predeterminado' => 0],
            ['id' => 219, 'Nombre' => 'XAR450', 'Descripcion' => 'CH.ANTIDESGASTE THISSEN', 'Predeterminado' => 0],
            ['id' => 223, 'Nombre' => 'XXXX', 'Descripcion' => 'XXXX (MIGRACION)', 'Predeterminado' => 0],
            ['id' => 224, 'Nombre' => 'XAR400', 'Descripcion' => 'XAR400 (MIGRACION)', 'Predeterminado' => 0],
            ['id' => 225, 'Nombre' => '12L14', 'Descripcion' => '12L14 (MIGRACION)', 'Predeterminado' => 0],
            ['id' => 226, 'Nombre' => 'SAE 8820', 'Descripcion' => 'SAE 8820 (MIGRACION)', 'Predeterminado' => 0],
            ['id' => 227, 'Nombre' => 'SAE J435', 'Descripcion' => 'SAE J435 (MIGRACION)', 'Predeterminado' => 0],
            ['id' => 228, 'Nombre' => 'AM.500', 'Descripcion' => 'AM.500 (MIGRACION)', 'Predeterminado' => 0],
            ['id' => 229, 'Nombre' => 'HARDOX 500', 'Descripcion' => 'ACERO ANTIDESGASTE', 'Predeterminado' => 0],
            ['id' => 230, 'Nombre' => 'A-36', 'Descripcion' => 'ACERO CONSTRUCCION', 'Predeterminado' => 0],
            ['id' => 231, 'Nombre' => '15B30', 'Descripcion' => 'ACERO MICROALEADO AL BORO CON ALTO MANGANESO(1, 5%)', 'Predeterminado' => 0],
            ['id' => 232, 'Nombre' => 'A.570 GR.36', 'Descripcion' => 'ACERO CONSTRUCCION', 'Predeterminado' => 0],
            ['id' => 233, 'Nombre' => 'AISI 1335', 'Descripcion' => 'ACERO ALEADO AL MANGANESO:0.33-0.38 C , 1.6-1.9 MN', 'Predeterminado' => 0],
            ['id' => 234, 'Nombre' => 'SAE 4145 M', 'Descripcion' => 'ALEADO (CIGÜEÑAL)', 'Predeterminado' => 0],
            ['id' => 235, 'Nombre' => 'SAE 4145 H', 'Descripcion' => 'ACERO REFINADO (CIGÜEÑALES)', 'Predeterminado' => 0],
            ['id' => 236, 'Nombre' => 'K 720', 'Descripcion' => 'ACERO TRABAJO EN FRIO', 'Predeterminado' => 0],
            ['id' => 237, 'Nombre' => 'THY.4116', 'Descripcion' => 'ACERO INOX.', 'Predeterminado' => 0],
            ['id' => 238, 'Nombre' => 'CAÑO ASTM 106 Gº B SCH 40', 'Descripcion' => 'CAÑO', 'Predeterminado' => 0],
            ['id' => 239, 'Nombre' => 'NOESP', 'Descripcion' => 'NO ESPECIFICADO', 'Predeterminado' => 0],
            ['id' => 240, 'Nombre' => 'NA', 'Descripcion' => 'NO APLICA', 'Predeterminado' => 0],
            ['id' => 241, 'Nombre' => 'SAE 8550', 'Descripcion' => 'ACERO PARA NITRURACION', 'Predeterminado' => 0],
            ['id' => 242, 'Nombre' => 'SAE 1026', 'Descripcion' => 'ACERO AL CARBONO', 'Predeterminado' => 0],
            ['id' => 243, 'Nombre' => 'AISI A2', 'Descripcion' => 'INDEFORMABLE', 'Predeterminado' => 0],
            ['id' => 244, 'Nombre' => 'HARDMOLD40', 'Descripcion' => 'P20 MODIFICADO / MOLDES PLASTICOS', 'Predeterminado' => 0],
            ['id' => 245, 'Nombre' => 'SAE J 431', 'Descripcion' => 'ACERO FUNDIDO', 'Predeterminado' => 0],
            ['id' => 246, 'Nombre' => 'SAE 1045 (F)', 'Descripcion' => 'ACERO AL CARBONO FORJADO', 'Predeterminado' => 0],
            ['id' => 247, 'Nombre' => 'K 2991', 'Descripcion' => 'ACERO HERRAMIENTA CORTE EN FRIO', 'Predeterminado' => 0],
        ];

        Material::insert($materiales);
        
        $tratamientos = [
            ['id' => 1, 'Nombre' => 'ALCO', 'Descripcion' => 'ALCOHOL', 'Coeficiente' => 0, 'Orden' => 50, 'Predeterminado' => 0, 'Archivado' => 1],
            ['id' => 2, 'Nombre' => 'VIATICOS', 'Descripcion' => 'TRABAJO REALIZADO EN PLANTA DEL CLIENTE', 'Coeficiente' => 0, 'Orden' => 49, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 3, 'Nombre' => 'ARE1', 'Descripcion' => 'ARENADO', 'Coeficiente' => 0, 'Orden' => 48, 'Predeterminado' => 0, 'Archivado' => 1],
            ['id' => 4, 'Nombre' => 'ARE2', 'Descripcion' => 'ARENADO', 'Coeficiente' => 0, 'Orden' => 47, 'Predeterminado' => 0, 'Archivado' => 1],
            ['id' => 5, 'Nombre' => 'CEM1', 'Descripcion' => 'CEMENTACION SIN TEMPLE 1 MM', 'Coeficiente' => 0, 'Orden' => 46, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 6, 'Nombre' => 'CEM2', 'Descripcion' => 'CEM SIN TEMPLE 1.5 MM', 'Coeficiente' => 0, 'Orden' => 45, 'Predeterminado' => 0, 'Archivado' => 1],
            ['id' => 7, 'Nombre' => 'CNTR', 'Descripcion' => 'CEMENTACION,NORM,TEMPLE,REVENIDO', 'Coeficiente' => 0, 'Orden' => 44, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 8, 'Nombre' => 'CPAR', 'Descripcion' => 'CEMENT.PARCIAL(CON PINTURA AISLANTE', 'Coeficiente' => 0, 'Orden' => 43, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 9, 'Nombre' => 'CTR1', 'Descripcion' => 'CEMENTACION,TEMPLE Y REVENIDO', 'Coeficiente' => 0, 'Orden' => 42, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 10, 'Nombre' => 'CTR2', 'Descripcion' => 'CEM,TEM,REV 1.5', 'Coeficiente' => 0, 'Orden' => 41, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 11, 'Nombre' => 'CTRA', 'Descripcion' => 'CEMENTACION,TEMPLE Y REV 1 MM', 'Coeficiente' => 0, 'Orden' => 40, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 12, 'Nombre' => 'CTRP', 'Descripcion' => 'CEMENTADO,TEM,REV Y PINTADO', 'Coeficiente' => 0, 'Orden' => 39, 'Predeterminado' => 0, 'Archivado' => 39],
            ['id' => 13, 'Nombre' => 'DIST', 'Descripcion' => 'ALIVIO TENSIONES S/ESPECIFICACIONES    EN HORNO', 'Coeficiente' => 0, 'Orden' => 11, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 14, 'Nombre' => 'END1', 'Descripcion' => 'ENDEREZADO', 'Coeficiente' => 0, 'Orden' => 13, 'Predeterminado' => 0, 'Archivado' => 1],
            ['id' => 15, 'Nombre' => 'ENDR', 'Descripcion' => 'ENDEREZADO', 'Coeficiente' => 0, 'Orden' => 15, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 16, 'Nombre' => 'ENSD', 'Descripcion' => 'ENSAYO DUREZA ROCKWELL,BRINELL,ETC', 'Coeficiente' => 0, 'Orden' => 38, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 17, 'Nombre' => 'SOL+ENVJ', 'Descripcion' => 'ENVEJECIDO ALEACION AL-CU-MG-SI', 'Coeficiente' => 0, 'Orden' => 37, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 18, 'Nombre' => 'HIP', 'Descripcion' => 'HIPERTEMPLE', 'Coeficiente' => 2, 'Orden' => 36, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 19, 'Nombre' => 'HOM', 'Descripcion' => 'HOMOGENEIZADO 1020º ENFR.AIRE', 'Coeficiente' => 0, 'Orden' => 35, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 20, 'Nombre' => 'HORA', 'Descripcion' => 'COBRO TRAT.POR HORA', 'Coeficiente' => 0, 'Orden' => 34, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 22, 'Nombre' => 'NOR', 'Descripcion' => 'NORMALIZADO', 'Coeficiente' => 0.6, 'Orden' => 8, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 24, 'Nombre' => 'NREV', 'Descripcion' => 'NORMALIZADO + REVENIDO', 'Coeficiente' => 0, 'Orden' => 31, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 25, 'Nombre' => 'REC1', 'Descripcion' => 'RECOCIDO ACEROS CONST.SUBCRITICO.', 'Coeficiente' => 0, 'Orden' => 9, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 26, 'Nombre' => 'REC2', 'Descripcion' => 'RECOCIDO FUNDICIONES,OTROS', 'Coeficiente' => 0, 'Orden' => 10, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 27, 'Nombre' => 'REC3', 'Descripcion' => 'REC.ACEROS INDEF-TRAB.CALIENTE,ETC', 'Coeficiente' => 0, 'Orden' => 0, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 28, 'Nombre' => 'REC4', 'Descripcion' => 'REC FUNF. ASTM 532 II', 'Coeficiente' => 0, 'Orden' => 14, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 29, 'Nombre' => 'RECG', 'Descripcion' => 'RECOCIDO GLOBULIZADO', 'Coeficiente' => 0, 'Orden' => 16, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 30, 'Nombre' => 'REV', 'Descripcion' => 'REVENIDO', 'Coeficiente' => 0.4, 'Orden' => 17, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 31, 'Nombre' => 'RPAR', 'Descripcion' => 'REVENIDO PARCIAL SOPLETE', 'Coeficiente' => 0, 'Orden' => 30, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 32, 'Nombre' => 'S+E', 'Descripcion' => 'SOLUBILIZADO+ENVEJECIDO ALEAC.AL-MG-CU', 'Coeficiente' => 0, 'Orden' => 29, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 34, 'Nombre' => 'SCDO', 'Descripcion' => 'SECADO MATERIAL MAMPOSTERIA', 'Coeficiente' => 0, 'Orden' => 27, 'Predeterminado' => 0, 'Archivado' => 1],
            ['id' => 35, 'Nombre' => 'SOL', 'Descripcion' => 'SOLUBILIZADO ALEAC. ALUMINIO MG-CU', 'Coeficiente' => 0, 'Orden' => 26, 'Predeterminado' => 0, 'Archivado' => 1],
            ['id' => 36, 'Nombre' => 'SOL1', 'Descripcion' => 'TRAT.SOLUCION ACERO INOX.', 'Coeficiente' => 0, 'Orden' => 25, 'Predeterminado' => 0, 'Archivado' => 1],
            ['id' => 37, 'Nombre' => 'TPAR', 'Descripcion' => 'TEMPLE PARCIAL', 'Coeficiente' => 0, 'Orden' => 24, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 38, 'Nombre' => 'TR01', 'Descripcion' => 'TEMPLE Y REVENIDO DE ACEROS DE CONSTRUCCION..', 'Coeficiente' => 0, 'Orden' => 1, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 39, 'Nombre' => 'TR02', 'Descripcion' => 'TEMPLE Y REVENIDO', 'Coeficiente' => 0, 'Orden' => 2, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 40, 'Nombre' => 'TR03', 'Descripcion' => 'TEMPLE Y REVENIDO', 'Coeficiente' => 0, 'Orden' => 3, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 41, 'Nombre' => 'TR04', 'Descripcion' => 'TEMPLE Y DOBLE REVENIDO', 'Coeficiente' => 0, 'Orden' => 4, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 42, 'Nombre' => 'TR05', 'Descripcion' => 'TEMPLE Y DOBLE REVENIDO', 'Coeficiente' => 0, 'Orden' => 5, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 43, 'Nombre' => 'TR06', 'Descripcion' => 'TEMPLE Y DOBLE REVENIDO', 'Coeficiente' => 0, 'Orden' => 6, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 44, 'Nombre' => 'TR07', 'Descripcion' => 'TRATAMIENTOS ESPECIALES', 'Coeficiente' => 0, 'Orden' => 7, 'Predeterminado' => 0, 'Archivado' => 1],
            ['id' => 45, 'Nombre' => 'TR01END', 'Descripcion' => 'TEMP REV 01 + ENDEREZADO', 'Coeficiente' => 0, 'Orden' => 23, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 46, 'Nombre' => 'TREN', 'Descripcion' => 'TEMP-REV-ENDEREZADO', 'Coeficiente' => 0, 'Orden' => 22, 'Predeterminado' => 0, 'Archivado' => 1],
            ['id' => 47, 'Nombre' => 'TR01U', 'Descripcion' => 'TEMPLE Y REVENIDO DE URGENCIA', 'Coeficiente' => 0, 'Orden' => 21, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 48, 'Nombre' => 'TR04URGENCIA', 'Descripcion' => 'TEMPLE Y REV DE URGENCIA INDEF. D3-01', 'Coeficiente' => 0, 'Orden' => 20, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 52, 'Nombre' => 'REC', 'Descripcion' => 'REC (MIGRACION)', 'Coeficiente' => 0, 'Orden' => 0, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 53, 'Nombre' => 'NTR1', 'Descripcion' => 'NTR1 (MIGRACION)', 'Coeficiente' => 0, 'Orden' => 0, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 54, 'Nombre' => 'DESC', 'Descripcion' => 'MATERIAL DESCONOCIDO', 'Coeficiente' => 0, 'Orden' => 0, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 55, 'Nombre' => 'XXX', 'Descripcion' => 'XXX', 'Coeficiente' => 0, 'Orden' => 0, 'Predeterminado' => 0, 'Archivado' => 1],
            ['id' => 57, 'Nombre' => 'MATDESC', 'Descripcion' => 'MATERIAL DESCONOCIDO', 'Coeficiente' => 0, 'Orden' => 0, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 61, 'Nombre' => 'T2R3', 'Descripcion' => 'TEMPLE Y DOBLE REVENIDO', 'Coeficiente' => 0, 'Orden' => 0, 'Predeterminado' => 0, 'Archivado' => 1],
            ['id' => 62, 'Nombre' => 'DISTV', 'Descripcion' => 'ESTABILIZADO DE TENSIONES POR VIBRACION EQUIPO  F62', 'Coeficiente' => 0, 'Orden' => 0, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 63, 'Nombre' => 'NO APLICA', 'Descripcion' => 'PARA VENTA DE CHATARRA', 'Coeficiente' => 0, 'Orden' => 0, 'Predeterminado' => 0, 'Archivado' => 0],
            ['id' => 67, 'Nombre' => 'TR01-PZAS.CH.', 'Descripcion' => 'TR LOTE MUY GRANDE   PIEZAS CHICAS', 'Coeficiente' => 0, 'Orden' => 0, 'Predeterminado' => 0, 'Archivado' => 0],
        ];

        Tratamiento::insert($tratamientos);

        CodigoComplejidad::create([
            'IdTratamiento' => 1,
            'Descripcion' => 'ARENADO',
            'Precio' => 150.00,
            'Divisa' => 'ARS',
            'PorcentajeCoeficiente' => 10.0,
            'Coeficiente' => 1.1,
            'CC' => 1,
            'FechaCreacion' => Carbon::now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now(),
            'ActualizadoPor' => 1,
            'Activo' => true,
            'IdTratamientoCodigoComplejidad' => 'TRT-CC-001',
        ]);

        CodigoComplejidad::create([
            'IdTratamiento' => 1,
            'Descripcion' => 'CONSTITUCION',
            'Precio' => 250.00,
            'Divisa' => 'ARS',
            'PorcentajeCoeficiente' => 20.0,
            'Coeficiente' => 1.2,
            'CC' => 2,
            'FechaCreacion' => Carbon::now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now(),
            'ActualizadoPor' => 1,
            'Activo' => true,
            'IdTratamientoCodigoComplejidad' => 'TRT-CC-002',
        ]);

        CodigoComplejidad::create([
            'IdTratamiento' => 1,
            'Descripcion' => 'REVENIDO',
            'Precio' => 350.00,
            'Divisa' => 'ARS',
            'PorcentajeCoeficiente' => 30.0,
            'Coeficiente' => 1.3,
            'CC' => 3,
            'FechaCreacion' => Carbon::now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now(),
            'ActualizadoPor' => 1,
            'Activo' => false,
            'IdTratamientoCodigoComplejidad' => 'TRT-CC-003',
        ]);

        CodigoComplejidad::create([
            'IdTratamiento' => 1,
            'Descripcion' => 'ARENADO',
            'Precio' => 150.00,
            'Divisa' => 'ARS',
            'PorcentajeCoeficiente' => 10.0,
            'Coeficiente' => 1.1,
            'CC' => 1,
            'FechaCreacion' => Carbon::now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now(),
            'ActualizadoPor' => 1,
            'Activo' => true,
            'IdTratamientoCodigoComplejidad' => 'TRT-CC-001',
        ]);

        CodigoComplejidad::create([
            'IdTratamiento' => 1,
            'Descripcion' => 'CONSTITUCION',
            'Precio' => 250.00,
            'Divisa' => 'ARS',
            'PorcentajeCoeficiente' => 20.0,
            'Coeficiente' => 1.2,
            'CC' => 2,
            'FechaCreacion' => Carbon::now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now(),
            'ActualizadoPor' => 1,
            'Activo' => true,
            'IdTratamientoCodigoComplejidad' => 'TRT-CC-002',
        ]);

        CodigoComplejidad::create([
            'IdTratamiento' => 1,
            'Descripcion' => 'REVENIDO',
            'Precio' => 350.00,
            'Divisa' => 'ARS',
            'PorcentajeCoeficiente' => 30.0,
            'Coeficiente' => 1.3,
            'CC' => 3,
            'FechaCreacion' => Carbon::now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now(),
            'ActualizadoPor' => 1,
            'Activo' => false,
            'IdTratamientoCodigoComplejidad' => 'TRT-CC-003',
        ]);

        CodigoComplejidad::create([
            'IdTratamiento' => 1,
            'Descripcion' => 'ARENADO',
            'Precio' => 150.00,
            'Divisa' => 'ARS',
            'PorcentajeCoeficiente' => 10.0,
            'Coeficiente' => 1.1,
            'CC' => 1,
            'FechaCreacion' => Carbon::now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now(),
            'ActualizadoPor' => 1,
            'Activo' => true,
            'IdTratamientoCodigoComplejidad' => 'TRT-CC-001',
        ]);

        CodigoComplejidad::create([
            'IdTratamiento' => 1,
            'Descripcion' => 'CONSTITUCION',
            'Precio' => 250.00,
            'Divisa' => 'ARS',
            'PorcentajeCoeficiente' => 20.0,
            'Coeficiente' => 1.2,
            'CC' => 2,
            'FechaCreacion' => Carbon::now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now(),
            'ActualizadoPor' => 1,
            'Activo' => true,
            'IdTratamientoCodigoComplejidad' => 'TRT-CC-002',
        ]);

        CodigoComplejidad::create([
            'IdTratamiento' => 1,
            'Descripcion' => 'REVENIDO',
            'Precio' => 350.00,
            'Divisa' => 'ARS',
            'PorcentajeCoeficiente' => 30.0,
            'Coeficiente' => 1.3,
            'CC' => 3,
            'FechaCreacion' => Carbon::now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now(),
            'ActualizadoPor' => 1,
            'Activo' => false,
            'IdTratamientoCodigoComplejidad' => 'TRT-CC-003',
        ]);

        CodigoComplejidad::create([
            'IdTratamiento' => 1,
            'Descripcion' => 'ARENADO',
            'Precio' => 150.00,
            'Divisa' => 'ARS',
            'PorcentajeCoeficiente' => 10.0,
            'Coeficiente' => 1.1,
            'CC' => 1,
            'FechaCreacion' => Carbon::now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now(),
            'ActualizadoPor' => 1,
            'Activo' => true,
            'IdTratamientoCodigoComplejidad' => 'TRT-CC-001',
        ]);

        CodigoComplejidad::create([
            'IdTratamiento' => 1,
            'Descripcion' => 'CONSTITUCION',
            'Precio' => 250.00,
            'Divisa' => 'ARS',
            'PorcentajeCoeficiente' => 20.0,
            'Coeficiente' => 1.2,
            'CC' => 2,
            'FechaCreacion' => Carbon::now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now(),
            'ActualizadoPor' => 1,
            'Activo' => true,
            'IdTratamientoCodigoComplejidad' => 'TRT-CC-002',
        ]);

        CodigoComplejidad::create([
            'IdTratamiento' => 1,
            'Descripcion' => 'REVENIDO',
            'Precio' => 350.00,
            'Divisa' => 'ARS',
            'PorcentajeCoeficiente' => 30.0,
            'Coeficiente' => 1.3,
            'CC' => 3,
            'FechaCreacion' => Carbon::now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now(),
            'ActualizadoPor' => 1,
            'Activo' => false,
            'IdTratamientoCodigoComplejidad' => 'TRT-CC-003',
        ]);

        OrdenTrabajo::create([
            'Letra' => 'X',
            'PuntoVenta' => '1',
            'Numero' => '64196',
            'NumeroCompleto' => 'OT X 0001-00064196',
            'NumeroRemitoCliente' => '4558',
            'FechaEmision' => '2017-05-10 14:00:00',
            'FechaVencimiento' => '2017-05-10 14:00:00',
            'AfectarPlanillaTurno' => '1',
            'CondicionPrecios' => 'A',
            'IdCliente' => '1',
            'RazonSocial' => 'MECANIZAR -LUIS FERRONI-',
            'IdCondicionIva' => '1',
            'TipoDocumentoCliente' => 'CUIT',
            'NumeroDocumentoCliente' => '20060801577',
            'Direccion' => 'DORREGO 140',
            'Localidad' => 'VILLA CONSTITUCION',
            'Provincia' => 'Santa Fe',
            'Estado' => 'PENDIENTE',
            'Total' => '0.00',
            'Observaciones' => null,
            'NumeroTurno' => '0',
            'ReferenciaTurno' => '2020',
            'AjusteCtaCtePlanillaTurno' => '0.00',
            'FechaCreacion' => '2017-05-10 14:00:00',
            'CreadoPor' => '1',
            'FechaActualizacion' => null,
            'ActualizadoPor' => '1',
            'Activo' => '1',
            'PuntoVentaNumero' => '1.64196',
            'IdClienteEstado' => '38,PENDIENTE',
            'IdClienteFechaEmisionPuntoVentaNumero' => '38,20241105,1,64196',
            'CantidadImpresiones' => '0',
            'CantidadEnviosPorCorreo' => '0',
            'Archivado' => '0',
        ]);

        ItemOrdenTrabajo::create([
            'IdOrdenTrabajo' => '1',
            'IdMaterial' => '1',
            'IdTratamiento' => '1',
            'IdDureza' => '1',
            'ItemNumero' => '1',
            'Descripcion' => 'CUBETA OT:7835',
            'NroDeposito' => '1',
            'Cantidad' => '3.000',
            'Peso' => '19.50',
            'CodigoComplejidad' => '0',
            'Coeficiente' => '0.000',
            'DurezaSolicitadaMinima' => '60',
            'DurezaSolicitadaMaxima' => '64',
            'PrecioUnitario' => '0.000',
            'Total' => '0.00',
            'AfectaPlanillaTurno' => '0',
            'ControlarStock' => '0',
            'Estado' => 'APROBADO',
            'FechaActualizacionEstado' => now(),
            'FechaCreacion' => now(),
            'CreadoPor' => '1',
            'FechaActualizacion' => now(),
            'ActualizadoPor' => '1',
            'Activo' => '1',
            'CertificadoEmitido' => '0',
            'CantidadCertificadosImpresos' => '1',
            'CantidadCertificadosEnviadosPorCorreo' => '1',
            'Observaciones' => null,
            'CantidadProgramaciones' => '2',
            'ConNotaEnvio' => '0',
            'IDEstadoConNotaEnvio' => '93494,APROBADO,0s',
            'IDIdOrdenTrabajoIdMaterialIdTratamientoCodigoComplejidadEstado' => '93494,55217,179,40.0.APROBADO',
        ]);

        ItemOrdenTrabajo::create([
            'IdOrdenTrabajo' => '1',
            'IdMaterial' => '1',
            'IdTratamiento' => '1',
            'IdDureza' => '1',
            'ItemNumero' => '1',
            'Descripcion' => 'CUBETA OT:634634',
            'NroDeposito' => '1',
            'Cantidad' => '3.000',
            'Peso' => '19.50',
            'CodigoComplejidad' => '0',
            'Coeficiente' => '0.000',
            'DurezaSolicitadaMinima' => '60',
            'DurezaSolicitadaMaxima' => '64',
            'PrecioUnitario' => '0.000',
            'Total' => '0.00',
            'AfectaPlanillaTurno' => '0',
            'ControlarStock' => '0',
            'Estado' => 'PENDIENTE',
            'FechaActualizacionEstado' => now(),
            'FechaCreacion' => now(),
            'CreadoPor' => '1',
            'FechaActualizacion' => now(),
            'ActualizadoPor' => '1',
            'Activo' => '1',
            'CertificadoEmitido' => '0',
            'CantidadCertificadosImpresos' => '1',
            'CantidadCertificadosEnviadosPorCorreo' => '1',
            'Observaciones' => null,
            'CantidadProgramaciones' => '2',
            'ConNotaEnvio' => '1',
            'IDEstadoConNotaEnvio' => '93494,APROBADO,0s',
            'IDIdOrdenTrabajoIdMaterialIdTratamientoCodigoComplejidadEstado' => '93494,55217,179,40.0.APROBADO',
        ]);

        ItemOrdenTrabajo::create([
            'IdOrdenTrabajo' => '1',
            'IdMaterial' => '1',
            'IdTratamiento' => '1',
            'IdDureza' => '1',
            'ItemNumero' => '1',
            'Descripcion' => 'CUBETA OT:12144',
            'NroDeposito' => '1',
            'Cantidad' => '3.000',
            'Peso' => '19.50',
            'CodigoComplejidad' => '0',
            'Coeficiente' => '0.000',
            'DurezaSolicitadaMinima' => '60',
            'DurezaSolicitadaMaxima' => '64',
            'PrecioUnitario' => '0.000',
            'Total' => '0.00',
            'AfectaPlanillaTurno' => '0',
            'ControlarStock' => '0',
            'Estado' => 'APROBADO',
            'FechaActualizacionEstado' => now(),
            'FechaCreacion' => now(),
            'CreadoPor' => '1',
            'FechaActualizacion' => now(),
            'ActualizadoPor' => '1',
            'Activo' => '1',
            'CertificadoEmitido' => '0',
            'CantidadCertificadosImpresos' => '1',
            'CantidadCertificadosEnviadosPorCorreo' => '1',
            'Observaciones' => null,
            'CantidadProgramaciones' => '2',
            'ConNotaEnvio' => '0',
            'IDEstadoConNotaEnvio' => '93494,APROBADO,0s',
            'IDIdOrdenTrabajoIdMaterialIdTratamientoCodigoComplejidadEstado' => '93494,55217,179,40.0.APROBADO',
        ]);

        $datos = [
            ['id' => 1, 'Nombre' => 'AI', 'Orden' => 1, 'Predeterminado' => 0],
            ['id' => 2, 'Nombre' => 'AG', 'Orden' => 2, 'Predeterminado' => 0],
            ['id' => 3, 'Nombre' => 'HO', 'Orden' => 3, 'Predeterminado' => 0],
            ['id' => 4, 'Nombre' => 'AC', 'Orden' => 4, 'Predeterminado' => 0],
            ['id' => 7, 'Nombre' => 'AF', 'Orden' => 5, 'Predeterminado' => 1],
            ['id' => 8, 'Nombre' => '780/AG', 'Orden' => 0, 'Predeterminado' => 0],
            ['id' => 9, 'Nombre' => '840/AC', 'Orden' => 0, 'Predeterminado' => 0],
            ['id' => 10, 'Nombre' => '850/AC', 'Orden' => 0, 'Predeterminado' => 0],
            ['id' => 11, 'Nombre' => '820/AC', 'Orden' => 0, 'Predeterminado' => 0],
            ['id' => 12, 'Nombre' => '800/AG', 'Orden' => 0, 'Predeterminado' => 0],
            ['id' => 13, 'Nombre' => 'AIF', 'Orden' => 0, 'Predeterminado' => 0],
        ];

        foreach ($datos as $dato) {
            MedioEnfriamiento::create($dato);
        }

        $datos = [
            ['id' => 1, 'Nombre' => 'TEMPLADO', 'Tipo' => 'PCO', 'Orden' => 1, 'Predeterminado' => 1, 'RequiereNumeracionSiempre' => 0, 'NombreTipo' => 'TEMPLADO,PCO'],
            ['id' => 2, 'Nombre' => 'REVENIDO', 'Tipo' => 'PCO', 'Orden' => 2, 'Predeterminado' => 0, 'RequiereNumeracionSiempre' => 1, 'NombreTipo' => 'REVENIDO,PCO'],
            ['id' => 3, 'Nombre' => 'RECOCIDO', 'Tipo' => 'PCO', 'Orden' => 3, 'Predeterminado' => 0, 'RequiereNumeracionSiempre' => 0, 'NombreTipo' => 'RECOCIDO,PCO'],
            ['id' => 4, 'Nombre' => 'NORMALIZADO', 'Tipo' => 'PCO', 'Orden' => 4, 'Predeterminado' => 0, 'RequiereNumeracionSiempre' => 0, 'NombreTipo' => 'NORMALIZADO,PCO'],
            ['id' => 5, 'Nombre' => 'DISTENSIONADO', 'Tipo' => 'PCO', 'Orden' => 5, 'Predeterminado' => 0, 'RequiereNumeracionSiempre' => 0, 'NombreTipo' => 'DISTENSIONADO,PCO'],
            ['id' => 6, 'Nombre' => 'CEM-SIN-TEMPLE', 'Tipo' => 'PCO', 'Orden' => 6, 'Predeterminado' => 0, 'RequiereNumeracionSiempre' => 0, 'NombreTipo' => 'CEM-SIN-TEMPLE,PCO'],
            ['id' => 7, 'Nombre' => 'CT', 'Tipo' => 'PCO', 'Orden' => 7, 'Predeterminado' => 0, 'RequiereNumeracionSiempre' => 0, 'NombreTipo' => 'CT,PCO'],
            ['id' => 8, 'Nombre' => 'ENSAYO', 'Tipo' => 'ENS', 'Orden' => 8, 'Predeterminado' => 0, 'RequiereNumeracionSiempre' => 0, 'NombreTipo' => 'ENSAYO,ENS'],
            ['id' => 12, 'Nombre' => 'TEMPLADO A LA LLAMA', 'Tipo' => 'ENS', 'Orden' => 0, 'Predeterminado' => 0, 'RequiereNumeracionSiempre' => 0, 'NombreTipo' => 'TEMPLADO A LA LLAMA,ENS'],
            ['id' => 14, 'Nombre' => 'ARENADO', 'Tipo' => 'ENS', 'Orden' => 0, 'Predeterminado' => 0, 'RequiereNumeracionSiempre' => 0, 'NombreTipo' => 'ARENADO,ENS'],
            ['id' => 15, 'Nombre' => 'REVENIDO A LA LLAMA', 'Tipo' => 'ENS', 'Orden' => 0, 'Predeterminado' => 0, 'RequiereNumeracionSiempre' => 0, 'NombreTipo' => 'REVENIDO A LA LLAMA,ENS'],
            ['id' => 16, 'Nombre' => 'SOLUBIZADO', 'Tipo' => 'PCO', 'Orden' => 0, 'Predeterminado' => 0, 'RequiereNumeracionSiempre' => 0, 'NombreTipo' => 'SOLUBIZADO,PCO'],
            ['id' => 17, 'Nombre' => 'ENVEJECIDO', 'Tipo' => 'PCO', 'Orden' => 0, 'Predeterminado' => 0, 'RequiereNumeracionSiempre' => 0, 'NombreTipo' => 'ENVEJECIDO,PCO'],
            ['id' => 18, 'Nombre' => 'HIPERTEMPLE', 'Tipo' => 'PCO', 'Orden' => 0, 'Predeterminado' => 0, 'RequiereNumeracionSiempre' => 0, 'NombreTipo' => 'HIPERTEMPLE,PCO'],
            ['id' => 19, 'Nombre' => 'DISTENSIONADO POR VIBRACION', 'Tipo' => 'ENS', 'Orden' => 0, 'Predeterminado' => 0, 'RequiereNumeracionSiempre' => 0, 'NombreTipo' => 'DISTENSIONADO POR VIBRACION,ENS'],
            ['id' => 20, 'Nombre' => 'NO APLICA', 'Tipo' => 'PNC', 'Orden' => 0, 'Predeterminado' => 0, 'RequiereNumeracionSiempre' => 0, 'NombreTipo' => 'NO APLICA,PNC'],
            ['id' => 21, 'Nombre' => 'PRECALENTADO', 'Tipo' => 'PCO', 'Orden' => 0, 'Predeterminado' => 0, 'RequiereNumeracionSiempre' => 0, 'NombreTipo' => 'PRECALENTADO,PCO'],
        ];

        foreach ($datos as $dato) {
            TipoProgramacion::create($dato);
        }

        $datos = [
            ['id' => 1, 'IdTratamiento' => 38, 'IdMaterial' => 160, 'IdTipoProgramacion' => 1, 'Temperatura' => 850, 'IdMedioEnfriamiento' => 7],
            ['id' => 2, 'IdTratamiento' => 38, 'IdMaterial' => 142, 'IdTipoProgramacion' => 1, 'Temperatura' => 840, 'IdMedioEnfriamiento' => 2],
            ['id' => 3, 'IdTratamiento' => 43, 'IdMaterial' => 44, 'IdTipoProgramacion' => 1, 'Temperatura' => 1020, 'IdMedioEnfriamiento' => 1],
            ['id' => 4, 'IdTratamiento' => 43, 'IdMaterial' => 189, 'IdTipoProgramacion' => 1, 'Temperatura' => 1020, 'IdMedioEnfriamiento' => 1],
            ['id' => 5, 'IdTratamiento' => 43, 'IdMaterial' => 213, 'IdTipoProgramacion' => 1, 'Temperatura' => 1020, 'IdMedioEnfriamiento' => 1],
            ['id' => 6, 'IdTratamiento' => 43, 'IdMaterial' => 105, 'IdTipoProgramacion' => 1, 'Temperatura' => 1020, 'IdMedioEnfriamiento' => 1],
            ['id' => 7, 'IdTratamiento' => 41, 'IdMaterial' => 104, 'IdTipoProgramacion' => 1, 'Temperatura' => 960, 'IdMedioEnfriamiento' => 4],
            ['id' => 8, 'IdTratamiento' => 41, 'IdMaterial' => 39, 'IdTipoProgramacion' => 1, 'Temperatura' => 960, 'IdMedioEnfriamiento' => 4],
            ['id' => 9, 'IdTratamiento' => 42, 'IdMaterial' => 33, 'IdTipoProgramacion' => 1, 'Temperatura' => 1020, 'IdMedioEnfriamiento' => 1],
            ['id' => 10, 'IdTratamiento' => 42, 'IdMaterial' => 31, 'IdTipoProgramacion' => 1, 'Temperatura' => 1020, 'IdMedioEnfriamiento' => 2],
            ['id' => 11, 'IdTratamiento' => 18, 'IdMaterial' => 28, 'IdTipoProgramacion' => 1, 'Temperatura' => 1020, 'IdMedioEnfriamiento' => 2],
            ['id' => 12, 'IdTratamiento' => 18, 'IdMaterial' => 29, 'IdTipoProgramacion' => 1, 'Temperatura' => 1020, 'IdMedioEnfriamiento' => 2],
            ['id' => 13, 'IdTratamiento' => 43, 'IdMaterial' => 44, 'IdTipoProgramacion' => 2, 'Temperatura' => 550, 'IdMedioEnfriamiento' => 1],
            ['id' => 18, 'IdTratamiento' => 9, 'IdMaterial' => 171, 'IdTipoProgramacion' => 6, 'Temperatura' => 930, 'IdMedioEnfriamiento' => 7],
            ['id' => 19, 'IdTratamiento' => 9, 'IdMaterial' => 171, 'IdTipoProgramacion' => 6, 'Temperatura' => 930, 'IdMedioEnfriamiento' => 9],
            ['id' => 20, 'IdTratamiento' => 9, 'IdMaterial' => 135, 'IdTipoProgramacion' => 7, 'Temperatura' => 930, 'IdMedioEnfriamiento' => 12],
            ['id' => 23, 'IdTratamiento' => 41, 'IdMaterial' => 104, 'IdTipoProgramacion' => 2, 'Temperatura' => 200, 'IdMedioEnfriamiento' => 1],
            ['id' => 24, 'IdTratamiento' => 41, 'IdMaterial' => 39, 'IdTipoProgramacion' => 2, 'Temperatura' => 200, 'IdMedioEnfriamiento' => 1],
            ['id' => 25, 'IdTratamiento' => 41, 'IdMaterial' => 85, 'IdTipoProgramacion' => 2, 'Temperatura' => 200, 'IdMedioEnfriamiento' => 1],
            ['id' => 27, 'IdTratamiento' => 13, 'IdMaterial' => 135, 'IdTipoProgramacion' => 5, 'Temperatura' => 580, 'IdMedioEnfriamiento' => 3],
            ['id' => 28, 'IdTratamiento' => 13, 'IdMaterial' => 142, 'IdTipoProgramacion' => 5, 'Temperatura' => 580, 'IdMedioEnfriamiento' => 3],
            ['id' => 29, 'IdTratamiento' => 13, 'IdMaterial' => 160, 'IdTipoProgramacion' => 5, 'Temperatura' => 580, 'IdMedioEnfriamiento' => 3],
            ['id' => 30, 'IdTratamiento' => 25, 'IdMaterial' => 160, 'IdTipoProgramacion' => 3, 'Temperatura' => 650, 'IdMedioEnfriamiento' => 3],
            ['id' => 31, 'IdTratamiento' => 27, 'IdMaterial' => 44, 'IdTipoProgramacion' => 3, 'Temperatura' => 850, 'IdMedioEnfriamiento' => 3],
            ['id' => 33, 'IdTratamiento' => 27, 'IdMaterial' => 39, 'IdTipoProgramacion' => 3, 'Temperatura' => 850, 'IdMedioEnfriamiento' => 3],
            ['id' => 34, 'IdTratamiento' => 27, 'IdMaterial' => 38, 'IdTipoProgramacion' => 3, 'Temperatura' => 850, 'IdMedioEnfriamiento' => 3],
            ['id' => 35, 'IdTratamiento' => 27, 'IdMaterial' => 91, 'IdTipoProgramacion' => 3, 'Temperatura' => 850, 'IdMedioEnfriamiento' => 3],
            ['id' => 36, 'IdTratamiento' => 25, 'IdMaterial' => 142, 'IdTipoProgramacion' => 3, 'Temperatura' => 650, 'IdMedioEnfriamiento' => 3],
            ['id' => 38, 'IdTratamiento' => 41, 'IdMaterial' => 40, 'IdTipoProgramacion' => 1, 'Temperatura' => 960, 'IdMedioEnfriamiento' => 4],
            ['id' => 39, 'IdTratamiento' => 22, 'IdMaterial' => 142, 'IdTipoProgramacion' => 4, 'Temperatura' => 870, 'IdMedioEnfriamiento' => 1],
            ['id' => 40, 'IdTratamiento' => 22, 'IdMaterial' => 160, 'IdTipoProgramacion' => 4, 'Temperatura' => 870, 'IdMedioEnfriamiento' => 1],
            ['id' => 41, 'IdTratamiento' => 43, 'IdMaterial' => 38, 'IdTipoProgramacion' => 1, 'Temperatura' => 1020, 'IdMedioEnfriamiento' => 1],
        ];

        PlantillaCarga::insert($datos);

        Programacion::create([
            'IdItemOrdenTrabajo' => '1',
            'NumeroProgramacion' => '1',
            'DurezaMinima' => '62',
            'DurezaMaxima' => '63',
            'IdTipoProgramacion' => '1',
            'Cantidad' => '2.000',
            'Apto' => 'SI',
            'Reproceso' => '0',
            'FechaCreacion' => '2025-05-27 20:16:17',
            'FechaCarga' => now(),
            'FechaDescarga' => now(),
            'Temperatura' => '150',
            'IdMedioEnfriamiento' => '1',
            'NumeroHorno' => '1',
            'EjecutadoPorOperador' => '1',
            'CreadoPor' => '1',
            'FechaActualizacion' => '2025-05-27 20:16:17',
            'ActualizadoPor' => '1',
            'Activo' => '1',
        ]);

        FactorPremio::create([
            'Nombre' => 'Proactividad',
            'ValorPredeterminado' => '1.00',
            'FechaCreacion' => now(),
            'CreadoPor' => '1',
            'FechaActualizacion' => now(),
            'ActualizadoPor' => '1',
            'Activo' => '1',
        ]);

        FactorPremio::create([
            'Nombre' => 'Presentismo',
            'ValorPredeterminado' => '2.00',
            'FechaCreacion' => now(),
            'CreadoPor' => '1',
            'FechaActualizacion' => now(),
            'ActualizadoPor' => '1',
            'Activo' => '1',
        ]);

        FactorPremio::create([
            'Nombre' => 'Predisposición Trab. en Equipo',
            'ValorPredeterminado' => '1.00',
            'FechaCreacion' => now(),
            'CreadoPor' => '1',
            'FechaActualizacion' => now(),
            'ActualizadoPor' => '1',
            'Activo' => '1',
        ]);

        FactorPremioUsuario::create([
            'IdUsuario' => '1',
            'IdFactorPremio' => '1',
            'Valor' => '2.00',
            'FechaCreacion' => now(),
            'CreadoPor' => '1',
            'FechaActualizacion' => now(),
            'ActualizadoPor' => '1',
            'Activo' => '1',
        ]);

        FactorPremioUsuario::create([
            'IdUsuario' => '1',
            'IdFactorPremio' => '2',
            'Valor' => '1.00',
            'FechaCreacion' => now(),
            'CreadoPor' => '1',
            'FechaActualizacion' => now(),
            'ActualizadoPor' => '1',
            'Activo' => '1',
        ]);

        Premio::create([
            'id' => '1',
            'Nombre' => 'JUNIO 2025',
            'FechaDesde' => now(),
            'FechaHasta' => now(),
            'Premio' => 1000000.22,
            'Estado' => 'COMPLETO',
            'FechaCreacion' => now(),
            'CreadoPor' => '1',
            'FechaActualizacion' => now(),
            'ActualizadoPor' => '1',
        ]);

        ItemPremio::create([
            'IdPremio' => '1',
            'IdUsuario' => 1,
            'PremioBase' => 300000,
            'IndiceBase' => 1,
            'Coeficiente' => 0.9,
            'Premio' => 300000 * 1 * 0.9,
            'FechaCreacion' => now(),
            'CreadoPor' => '1',
            'FechaActualizacion' => now(),
            'ActualizadoPor' => '1',
        ]);

    }
}
