<?php

namespace Database\Seeders;

use App\Models\Arti;
use App\Models\Banco;
use App\Models\Chequecobro;
use App\Models\Cobro;
use App\Models\CondicionVenta;
use App\Models\ConfiguracionGlobal;
use App\Models\CuentaOtrosEgresos;
use App\Models\DestinoCheque;
use App\Models\FactorPremio;
use App\Models\FactorPremioUsuario;
use App\Models\ItemPremio;
use App\Models\Premio;
use App\Models\FacturaVenta;
use App\Models\ImpuestoIva;
use App\Models\ItemFacturaVenta;
use App\Models\ItemMinutaVenta;
use App\Models\ItemNotaCreditoVenta;
use App\Models\ItemNotaEnvio;
use App\Models\ItemReciboVenta;
use App\Models\MinutaVenta;
use App\Models\MovimientoCuentaGastos;
use App\Models\NotaCreditoVenta;
use App\Models\NotaEnvio;
use App\Models\Periodo;
use App\Models\ReciboVenta;
use App\Models\TransferenciaCobro;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class VentasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        ConfiguracionGlobal::create([
            'RazonSocialEmpresa' => 'DURMETAL',
            'DomicilioEmpresa' => 'INDEPENDENCIA 1456',
            'TelefonoEmpresa' => '(03400) 47 - 6320',
            'CUITEmpresa' => '30-71723799-0',
            'IIBBEmpresa' => '101-844490-3',
            'FechaInicioActividadesEmpresa' => '2022-01-01',
            'LocalidadEmpresa' => 'VILLA CONSTITUCION',
            'ProvinciaEmpresa' => 'SANTA FE.',
            'CodigoSucursal' => 0,
            'ImporteMinimoRetencionIIBB' => 6000.00,
            'CodigoPostalEmpresa' => 2919,
            'NroAgenteEmpresa' => null,
            'EsAgenteRetencionGanancias' => false,
            'EsAgenteRetencionIIBB' => false,
            'CuentaEmailMembretes' => 'durmetal@durmetal.com.ar',
            'CuentaEmail' => 'durmetal@durmetal.com.ar',
            'ServidorSMTP' => 'ev000653.ferozo.com',
            'PuertoSMTP' => '587',
            'UsuarioSMTP' => 'durmetal@durmetal.com.ar',
            'ClaveSMTP' => 'Magdalena07',
            'TiempoDeEsperaSMTP' => 30,
            'OpcionSMTP' => 0,
            'CuentaEmailCCO' => null,
            'RemitenteCCO' => false,
            'XMLLoginTicketRequest' => '<loginTicketRequest><header><source>SERIALNUMBER=CUIT 20060747432, CN=cert01</source><destination>cn=wsaa,o=afip,c=ar,serialNumber=CUIT 33693450239</destination><uniqueId></uniqueId><generationTime></generationTime><expirationTime></expirationTime></header><service></service></loginTicketRequest>',
            'ModoOperacionFE' => 'PROD',
            'RutaCertificadoFE' => 'C:\Afip\cert01prod.pfx',
            'ClaveCertificadoFE' => '65z9mKF2hVag',
            'ClaveForzarValidacionCtaCteCliente' => '2QHn103r',
            'FechaCreacion' => null,
            'CreadoPor' => 1,
            'FechaActualizacion' => null,
            'ActualizadoPor' => 1,
            'Activo' => 1,
            'CuentaEmailCertificados' => 'controldecalidad@durmetal.com.ar',
            'ServidorSMTPCertificados' => 'ev000653.ferozo.com',
            'PuertoSMTPCertificados' => '587',
            'UsuarioSMTPCertificados' => 'controldecalidad@durmetal.com.ar',
            'ClaveSMTPCertificados' => 'Sae10454140',
            'TiempoDeEsperaSMTPCertificados' => 30,
            'OpcionSMTPCertificados' => 0,
            'CuentaEmailCCOCertificados' => null,
            'RemitenteCCOCertificados' => false,
            'ValidarProgramacionesSinDatosDurezas' => 1,
            'NombreLogo' => 'logo_empresa.png',
            'PlazoVencimientoFactura' => 7,
            'USD_ARS' => 1010.25,
            'FechaActualizacionUSD_ARS' => Carbon::now()->subDays(1),
            'FechaEmisionValidaDesde' => 30,
            'FechaEmisionValidaHasta' => 1,
        ]);

        FactorPremio::create([
            'Nombre' => 'Proactividad',
            'ValorPredeterminado' => '1.00',
            'FechaCreacion' => now(),
            'CreadoPor' => '1',
            'FechaActualizacion' => now(),
            'ActualizadoPor' => '1',
            'Activo' => '1',
        ]);

        FactorPremio::create([
            'Nombre' => 'Presentismo',
            'ValorPredeterminado' => '2.00',
            'FechaCreacion' => now(),
            'CreadoPor' => '1',
            'FechaActualizacion' => now(),
            'ActualizadoPor' => '1',
            'Activo' => '1',
        ]);

        FactorPremio::create([
            'Nombre' => 'Predisposición Trab. en Equipo',
            'ValorPredeterminado' => '1.00',
            'FechaCreacion' => now(),
            'CreadoPor' => '1',
            'FechaActualizacion' => now(),
            'ActualizadoPor' => '1',
            'Activo' => '1',
        ]);

        FactorPremioUsuario::create([
            'IdUsuario' => '1',
            'IdFactorPremio' => '1',
            'Valor' => '2.00',
            'FechaCreacion' => now(),
            'CreadoPor' => '1',
            'FechaActualizacion' => now(),
            'ActualizadoPor' => '1',
            'Activo' => '1',
        ]);

        FactorPremioUsuario::create([
            'IdUsuario' => '1',
            'IdFactorPremio' => '2',
            'Valor' => '1.00',
            'FechaCreacion' => now(),
            'CreadoPor' => '1',
            'FechaActualizacion' => now(),
            'ActualizadoPor' => '1',
            'Activo' => '1',
        ]);

        Premio::create([
            'Nombre' => 'JUNIO 2025',
            'FechaDesde' => now(),
            'FechaHasta' => now(),
            'Premio' => 1000000.22,
            'Estado' => 'COMPLETO',
            'FechaCreacion' => now(),
            'CreadoPor' => '1',
            'FechaActualizacion' => now(),
            'ActualizadoPor' => '1',
        ]);

        ItemPremio::create([
            'IdPremio' => '1',
            'IdUsuario' => 1,
            'PremioBase' => 300000,
            'IndiceBase' => 1,
            'Coeficiente' => 0.9,
            'Premio' => 300000 * 1 * 0.9,
            'FechaCreacion' => now(),
            'CreadoPor' => '1',
            'FechaActualizacion' => now(),
            'ActualizadoPor' => '1',
        ]);

        NotaEnvio::create([
            'Letra' => 'X',
            'PuntoVenta' => 1,
            'Numero' => 1001,
            'NumeroCompleto' => 'NE X 0001-00001001',
            'FechaEmision' => Carbon::now()->subDays(2)->toDateString(),
            'FechaVencimiento' => Carbon::now()->addDays(30)->toDateString(),
            'AfectarPlanillaTurno' => 1,
            'CondicionPrecios' => 'Contado',
            'IdCliente' => 1,
            'RazonSocial' => 'DESARROLLOS INDUSTRIALES',
            'IdCondicionIva' => 1,
            'TipoDocumento' => 'CUIT',
            'NumeroDocumentoCliente' => '30708681896',
            'Direccion' => 'CHACO 74 SAN NICOLÁS',
            'Localidad' => 'San Nicolás de los Arroyos',
            'Provincia' => 'Buenos Aires',
            'Estado' => 'PENDIENTE',
            'TipoOperacion' => 'Normal',
            'PorcentajeDescuento' => 10.00,
            'Neto' => 10000.00,
            'IVA' => 2100.00,
            'Total' => 12100.00,
            'Observaciones' => 'Entrega en 48 hs.',
            'NumeroTurno' => 1234,
            'ReferenciaTurno' => 5678,
            'AjusteCtaCtePlanillaTurno' => 0.00,
            'FechaCreacion' => Carbon::now()->subDays(2)->toDateString(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now()->toDateString(),
            'ActualizadoPor' => 1,
            'Activo' => 1,
            'PuntoVentaNumero' => '0001',
            'CantidadImpresiones' => 1,
            'CantidadEnviosPorCorreo' => 0,
        ]);

        ItemNotaEnvio::create([
            'IdNotaEnvio' => 1,
            'IdItemOrdenTrabajo' => 1,
            'ItemNumero' => 1,
            'Descripcion' => 'ARE1-16CrMn5-CUBETA OT:12144-???? 4558',
            'Cantidad' => 2,
            'Peso' => 1.5,
            'CodigoComplejidad' => 3,
            'Coeficiente' => 1.25,
            'PrecioUnitario' => 5000.00,
            'PorcentajeDescuento' => 10.00,
            'Total' => 9000.00,
            'Estado' => 'PENDIENTE',
            'FechaCreacion' => Carbon::now()->subDays(1)->toDateString(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now()->toDateString(),
            'ActualizadoPor' => 1,
            'Activo' => 1,
        ]);

        ItemNotaEnvio::create([
            'IdNotaEnvio' => 1,
            'IdItemOrdenTrabajo' => 1,
            'ItemNumero' => 2,
            'Descripcion' => 'ARE1-16CrMn5-CUBETA OT:12144-???? 4558',
            'Cantidad' => 2,
            'Peso' => 1.5,
            'CodigoComplejidad' => 3,
            'Coeficiente' => 1.25,
            'PrecioUnitario' => 5000.00,
            'PorcentajeDescuento' => 10.00,
            'Total' => 9000.00,
            'Estado' => 'PENDIENTE',
            'FechaCreacion' => Carbon::now()->subDays(1)->toDateString(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now()->toDateString(),
            'ActualizadoPor' => 1,
            'Activo' => 1,
        ]);

        NotaEnvio::create([
            'Letra' => 'X',
            'PuntoVenta' => 1,
            'Numero' => 1001,
            'NumeroCompleto' => 'NE X 0002-00001001',
            'FechaEmision' => Carbon::now()->subDays(2)->toDateString(),
            'FechaVencimiento' => Carbon::now()->addDays(30)->toDateString(),
            'AfectarPlanillaTurno' => 1,
            'CondicionPrecios' => 'Contado',
            'IdCliente' => 1,
            'RazonSocial' => 'DESARROLLOS INDUSTRIALES',
            'IdCondicionIva' => 1,
            'TipoDocumento' => 'CUIT',
            'NumeroDocumentoCliente' => '30708681896',
            'Direccion' => 'CHACO 74 SAN NICOLÁS',
            'Localidad' => 'San Nicolás de los Arroyos',
            'Provincia' => 'Buenos Aires',
            'Estado' => 'COMPLETO',
            'TipoOperacion' => 'Normal',
            'PorcentajeDescuento' => 10.00,
            'Neto' => 10000.00,
            'IVA' => 2100.00,
            'Total' => 12100.00,
            'Observaciones' => 'Entrega en 48 hs.',
            'NumeroTurno' => 1234,
            'ReferenciaTurno' => 5678,
            'AjusteCtaCtePlanillaTurno' => 0.00,
            'FechaCreacion' => Carbon::now()->subDays(2)->toDateString(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now()->toDateString(),
            'ActualizadoPor' => 1,
            'Activo' => 1,
            'PuntoVentaNumero' => '0001',
            'CantidadImpresiones' => 1,
            'CantidadEnviosPorCorreo' => 0,
        ]);

        ItemNotaEnvio::create([
            'IdNotaEnvio' => 1,
            'IdItemOrdenTrabajo' => 1,
            'ItemNumero' => 1,
            'Descripcion' => 'VIATICOS-16CrMn5-CUBETA OT:7835-???? 4558',
            'Cantidad' => 2,
            'Peso' => 1.5,
            'CodigoComplejidad' => 3,
            'Coeficiente' => 1.25,
            'PrecioUnitario' => 5000.00,
            'PorcentajeDescuento' => 10.00,
            'Total' => 9000.00,
            'Estado' => 'PENDIENTE',
            'FechaCreacion' => Carbon::now()->subDays(1)->toDateString(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now()->toDateString(),
            'ActualizadoPor' => 1,
            'Activo' => 1,
        ]);

        NotaEnvio::create([
            'Letra' => 'X',
            'PuntoVenta' => 1,
            'Numero' => 1001,
            'NumeroCompleto' => 'NE X 0003-00001001',
            'FechaEmision' => Carbon::now()->subDays(2)->toDateString(),
            'FechaVencimiento' => Carbon::now()->addDays(30)->toDateString(),
            'AfectarPlanillaTurno' => 1,
            'CondicionPrecios' => 'Contado',
            'IdCliente' => 1,
            'RazonSocial' => 'DESARROLLOS INDUSTRIALES',
            'IdCondicionIva' => 1,
            'TipoDocumento' => 'CUIT',
            'NumeroDocumentoCliente' => '30708681896',
            'Direccion' => 'CHACO 74 SAN NICOLÁS',
            'Localidad' => 'San Nicolás de los Arroyos',
            'Provincia' => 'Buenos Aires',
            'Estado' => 'PENDIENTE',
            'TipoOperacion' => 'Normal',
            'PorcentajeDescuento' => 10.00,
            'Neto' => 10000.00,
            'IVA' => 2100.00,
            'Total' => 12100.00,
            'Observaciones' => 'Entrega en 48 hs.',
            'NumeroTurno' => 1234,
            'ReferenciaTurno' => 5678,
            'AjusteCtaCtePlanillaTurno' => 0.00,
            'FechaCreacion' => Carbon::now()->subDays(2)->toDateString(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now()->toDateString(),
            'ActualizadoPor' => 1,
            'Activo' => 1,
            'PuntoVentaNumero' => '0001',
            'CantidadImpresiones' => 1,
            'CantidadEnviosPorCorreo' => 0,
        ]);

        FacturaVenta::create([
            'Letra' => 'A',
            'PuntoVenta' => 1,
            'Numero' => 1001,
            'NumeroCompleto' => 'FC A 0001-00001001',
            'FechaEmision' => now(),
            'FechaVencimiento' => '2025-12-31',
            'FechaEstadisticas' => now(),
            'TipoOperacion' => 'Normal',
            'CondicionPrecios' => 'Contado',
            'IdCliente' => 1,
            'RazonSocial' => 'DESARROLLOS INDUSTRIALES',
            'TipoDocumentoCliente' => 'CUIT',
            'NumeroDocumentoCliente' => 30708681896,
            'Direccion' => 'CHACO 74 SAN NICOLÁS',
            'Localidad' => 'San Nicolás de los Arroyos',
            'IdCondicionIva' => 1,
            'CondicionVenta' => 'Contado',
            'Neto' => 10000,
            'NetoNoGravado' => 0,
            'Exento' => 0,
            'IVA' => 2100,
            'ImpuestoInterno' => 0,
            'Total' => 12100,
            'AjusteCtaCtePlanillaTurno' => 0,
            'Estado' => 'PENDIENTE',
            'CAE' => '12345678901234',
            'FechaVencimientoCAE' => '2025-12-31',
            'IdSolicitudCAE' => 999,
            'Observaciones' => 'Sin observaciones',
            'NumeroTurno' => 123,
            'ReferenciaTurno' => 456,
            'AfectarPlanillaTurno' => 1,
            'EsNotaDeDebito' => false,
            'NroFacturaNotaDebito' => null,
            'EntregarMercaderiaConRemitos' => 1,
            'FechaCreacion' => now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => now(),
            'ActualizadoPor' => 1,
            'Activo' => 1,
            'CantidadImpresiones' => 1,
            'CantidadEnviosPorCorreo' => 0
        ]);

        FacturaVenta::create([
            'Letra' => 'A',
            'PuntoVenta' => 1,
            'Numero' => 1001,
            'NumeroCompleto' => 'ND A 0001-00001001',
            'FechaEmision' => now(),
            'FechaVencimiento' => '2025-12-31',
            'FechaEstadisticas' => now(),
            'TipoOperacion' => 'Normal',
            'CondicionPrecios' => 'Contado',
            'IdCliente' => 1,
            'RazonSocial' => 'DESARROLLOS INDUSTRIALES',
            'TipoDocumentoCliente' => 'CUIT',
            'NumeroDocumentoCliente' => 30708681896,
            'Direccion' => 'CHACO 74 SAN NICOLÁS',
            'Localidad' => 'San Nicolás de los Arroyos',
            'IdCondicionIva' => 1,
            'CondicionVenta' => 'Contado',
            'Neto' => 10000,
            'NetoNoGravado' => 0,
            'Exento' => 0,
            'IVA' => 2100,
            'ImpuestoInterno' => 0,
            'Total' => 12100,
            'AjusteCtaCtePlanillaTurno' => 0,
            'Estado' => 'COMPLETO',
            'CAE' => '12345678901234',
            'FechaVencimientoCAE' => '2025-12-31',
            'IdSolicitudCAE' => 999,
            'Observaciones' => 'Sin observaciones',
            'NumeroTurno' => 123,
            'ReferenciaTurno' => 456,
            'AfectarPlanillaTurno' => 1,
            'EsNotaDeDebito' => true,
            'NroFacturaNotaDebito' => null,
            'EntregarMercaderiaConRemitos' => 1,
            'FechaCreacion' => now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => now(),
            'ActualizadoPor' => 1,
            'Activo' => 1,
            'CantidadImpresiones' => 1,
            'CantidadEnviosPorCorreo' => 0
        ]);

        ImpuestoIva::create([
            'Nombre' => 'IVA 21%',
            'Tasa' => 21.00,
            'FechaCreacion' => Carbon::now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now(),
            'ActualizadoPor' => 1,
            'Activo' => 1,
            'Observaciones' => null
        ]);

        ImpuestoIva::create([
            'Nombre' => 'IVA 10.5%',
            'Tasa' => 10.50,
            'FechaCreacion' => Carbon::now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now(),
            'ActualizadoPor' => 1,
            'Activo' => 1,
            'Observaciones' => null
        ]);

        ImpuestoIva::create([
            'Nombre' => 'IVA Exento',
            'Tasa' => 0.00,
            'FechaCreacion' => Carbon::now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now(),
            'ActualizadoPor' => 1,
            'Activo' => 1,
            'Observaciones' => null
        ]);

        ImpuestoIva::create([
            'Nombre' => 'IVA 27%',
            'Tasa' => 27.00,
            'FechaCreacion' => Carbon::now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now(),
            'ActualizadoPor' => 1,
            'Activo' => 0,
            'Observaciones' => null
        ]);

        ImpuestoIva::create([
            'Nombre' => 'IVA 2.5%',
            'Tasa' => 2.50,
            'FechaCreacion' => Carbon::now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now(),
            'ActualizadoPor' => 1,
            'Activo' => 0,
            'Observaciones' => null
        ]);

        ImpuestoIva::create([
            'Nombre' => 'No Gravado',
            'Tasa' => 0.00,
            'FechaCreacion' => Carbon::now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now(),
            'ActualizadoPor' => 1,
            'Activo' => 1,
            'Observaciones' => null
        ]);

        ImpuestoIva::create([
            'Nombre' => 'IVA 0%',
            'Tasa' => 0.00,
            'FechaCreacion' => Carbon::now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now(),
            'ActualizadoPor' => 1,
            'Activo' => 1,
            'Observaciones' => null
        ]);

        NotaCreditoVenta::create([
            'IdFacturaVenta' => 1,
            'Letra' => 'A',
            'PuntoVenta' => 1,
            'Numero' => 2001,
            'NumeroCompleto' => 'NC A 0001-00002001',
            'FechaEmision' => Carbon::now()->subDays(1),
            'FechaVencimiento' => Carbon::now()->addDays(30),
            'FechaEstadisticas' => Carbon::now(),
            'TipoOperacion' => 'Devolucion',
            'CondicionPrecios' => 'Contado',
            'IdCliente' => 1,
            'RazonSocial' => 'DESARROLLOS INDUSTRIALES',
            'IdCondicionIva' => 1,
            'TipoDocumentoCliente' => 'CUIT',
            'NumeroDocumentoCliente' => '30708681896',
            'Direccion' => 'CHACO 74 SAN NICOLÁS',
            'Localidad' => 'San Nicolás de los Arroyos',
            'Neto' => 5000.00,
            'NetoNoGravado' => 0.00,
            'IVA' => 1050.00,
            'Exento' => 0.00,
            'ImpuestoInterno' => 0.00,
            'Total' => 6050.00,
            'AjusteCtaCtePlanillaTurno' => 0.00,
            'Estado' => 'Emitida',
            'CAE' => '45678901234567',
            'FechaVencimientoCAE' => Carbon::now()->addDays(15),
            'IdSolicitudCAE' => 123456,
            'Observaciones' => 'Devolución de servicio',
            'NumeroTurno' => 321,
            'ReferenciaTurno' => 654,
            'AfectarPlanillaTurno' => false,
            'FechaCreacion' => Carbon::now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now(),
            'ActualizadoPor' => 1,
            'Activo' => 1,
            'CantidadImpresiones' => 1,
            'CantidadEnviosPorCorreo' => 0
        ]);

        ItemNotaCreditoVenta::create([
            'IdNotaCreditoVenta' => 1,
            'ItemNumero' => 1,
            'IdArticulo' => 1,
            'Descripcion' => 'Devolución por servicio no realizado',
            'NroDeposito' => 1,
            'Cantidad' => 1,
            'PrecioCosto' => 4000.00,
            'PrecioUnitarioNeto' => 5000.00,
            'PrecioUnitario' => 6050.00,
            'AlicuotaIVA' => 21.00,
            'ImpuestoInterno' => 0.00,
            'ImpuestoCombustible' => 0.00,
            'ImpuestoTV' => 0.00,
            'ImpuestosInternos' => 0.00,
            'Neto' => 5000.00,
            'IdImpuestoIva' => 1,
            'IVA' => 1050.00,
            'Total' => 6050.00,
            'AfectarPlanillaTurno' => false,
            'ControlarStock' => false,
            'FechaCreacion' => Carbon::now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now(),
            'ActualizadoPor' => 1,
            'Activo' => 1
        ]);

        ReciboVenta::create([
            'Letra' => 'A',
            'PuntoVenta' => 1,
            'Numero' => 3001,
            'NumeroCompleto' => 'RE A 0001-00003001',
            'FechaEmision' => Carbon::now(),
            'IdCliente' => 1,
            'RazonSocial' => 'DESARROLLOS INDUSTRIALES',
            'IdCondicionIva' => 1,
            'TipoDocumentoCliente' => 'CUIT',
            'NumeroDocumentoCliente' => '30708681896',
            'Direccion' => 'CHACO 74 SAN NICOLÁS',
            'Localidad' => 'San Nicolás de los Arroyos',
            'RetencionDREI' => 0,
            'RetencionIIBB' => 0,
            'RetencionIVA' => 0,
            'RetencionGanancias' => 0,
            'RetencionSUSS' => 0,
            'Estado' => 'Emitido',
            'Total' => 15000.00,
            'Observaciones' => 'Pago recibido',
            'NumeroTurno' => 789,
            'ReferenciaTurno' => 987,
            'AfectarPlanillaTurno' => 1,
            'FechaCreacion' => Carbon::now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now(),
            'ActualizadoPor' => 1,
            'Activo' => 1,
            'LetraNumeroCompleto' => 'A-0001-00003001',
            'CantidadImpresiones' => 1,
            'CantidadEnviosPorCorreo' => 0,
            'DescripcionSaldoTransportado' => 'Saldo a favor anterior',
            'ImporteSaldoTransportado' => 0.00
        ]);
        
        ItemReciboVenta::create([
            'IdReciboVenta' => 1,
            'IdFacturaVenta' => 1,
            'Descripcion' => 'Pago parcial factura 1001',
            'Total' => 5000.00,
            'FechaCreacion' => Carbon::now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now(),
            'ActualizadoPor' => 1,
            'Activo' => 1
        ]);

        MinutaVenta::create([
            'Numero' => 1,
            'NumeroCompleto' => 'MV-2025-' . str_pad(1, 4, '0', STR_PAD_LEFT),
            'FechaEmision' => Carbon::now()->subDays(rand(1, 30)),
            'IdCliente' => 1,
            'TipoOperacion' => 'Venta',
            'Estado' => 'Emitido',
            'Total' => rand(1000, 5000),
            'FechaCreacion' => Carbon::now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now(),
            'ActualizadoPor' => 1,
            'Activo' => true,
        ]);

        ItemMinutaVenta::create([
            'IdMinutaVenta' => 1,
            'Descripcion' => 'Producto o servicio',
            'Total' => rand(200, 1000),
            'FechaCreacion' => Carbon::now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now(),
            'ActualizadoPor' => 1,
            'Activo' => true,
        ]);

        $banco = Banco::create([
            'Nombre' => 'Banco Nación',
            'FechaCreacion' => now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => now(),
            'ActualizadoPor' => 1,
            'Predeterminado' => 1,
            'Activo' => true,
            'Archivado' => false,
        ]);

        $cobro = Cobro::create([
            'IdReciboVenta' => 1,
            'FormaPago' => 'TRANSFERENCIA',
            'Descripcion' => 'Banco Nación',
            'Total' => 1500.00,
            'FechaCreacion' => now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => now(),
            'ActualizadoPor' => 1,
            'Activo' => true,
        ]);

        TransferenciaCobro::create([
            'IdCobro' => $cobro->id,
            'IdBanco' => $banco->id,
        ]);

        DestinoCheque::create([
            'Nombre' => 'En cartera',
            'FechaCreacion' => now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => now(),
            'ActualizadoPor' => 1,
            'Activo' => true,
        ]);

        DestinoCheque::create([
            'Nombre' => 'Depositado',
            'FechaCreacion' => now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => now(),
            'ActualizadoPor' => 1,
            'Activo' => true,
        ]);

        DestinoCheque::create([
            'Nombre' => 'Endosado',
            'FechaCreacion' => now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => now(),
            'ActualizadoPor' => 1,
            'Activo' => true,
        ]);

        DestinoCheque::create([
            'Nombre' => 'Rechazado',
            'FechaCreacion' => now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => now(),
            'ActualizadoPor' => 1,
            'Activo' => true,
        ]);

        Chequecobro::create([
            'IdCobro' => 1,
            'FechaEmision' => now(),
            'FechaAcreditacion' => now()->addDays(5),
            'IdBanco' => 1,
            'Numero' => 123456,
            'IdDestinoCheque' => 1,
            'Plaza' => 101,
            'eCheck' => false,
            'FechaCreacion' => now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => now(),
            'ActualizadoPor' => 1,
            'Activo' => true,
        ]);

        $condiciones_venta = [
            ['id' => 1, 'Nombre' => 'Contado', 'Seleccionado' => 0],
            ['id' => 2, 'Nombre' => 'Tarjeta de Débito', 'Seleccionado' => 0],
            ['id' => 3, 'Nombre' => 'Tarjeta de Crédito', 'Seleccionado' => 0],
            ['id' => 4, 'Nombre' => 'Cuenta Corriente 30 dias ff', 'Seleccionado' => 0],
            ['id' => 5, 'Nombre' => 'Cheque 60 dias ff.', 'Seleccionado' => 0],
            ['id' => 6, 'Nombre' => 'Cheque o transf. 7 dias ff.', 'Seleccionado' => 1],
            ['id' => 7, 'Nombre' => 'Cta Cte 15 días ff', 'Seleccionado' => 0],
        ];

        CondicionVenta::insert($condiciones_venta);

        Arti::create([
            'CODART' => 1,
            'RUBART' => 1,
            'MAAART' => 1,
            'ROBART' => 0,
            'PROART' => 0,
            'IdImpuestoIva' => 1,
            'DESART' => 'TRATAMIENTO TERMICO',
            'CTRART' => null,
            'BARART' => null,
            'IVAART' => 0,
            'UNIART' => null,
            'CANART' => 0.00,
            'ImpuestoInterno' => 0,
            'ITC' => 0,
            'TV' => 0,
            'ITCART' => 0,
            'MARART' => 0,
            'MA2ART' => 0,
            'MA3ART' => 0,
            'PR0ART' => 0,
            'PR1ART' => 0,
            'PR2ART' => 0,
            'PR3ART' => 0,
            'PR4ART' => 0,
            'PR5ART' => 0,
            'PR6ART' => 0,
            'PR7ART' => 0,
            'PR8ART' => 0,
            'ACTART' => 0,
            'MINART' => 0,
            'VTOART' => 0,
            'AR1ART' => 0,
            'AR2ART' => 0,
            'AR3ART' => 0,
            'AR4ART' => 0,
            'BRUART' => 0,
            'PB1ART' => 0,
            'PB2ART' => 0,
            'PB3ART' => 0,
            'CA1ART' => 0,
            'CA2ART' => 0,
            'CA3ART' => 0,
            'CA4ART' => 0,
            'GA1ART' => 0,
            'GA2ART' => 0,
            'GA3ART' => 0,
            'GA4ART' => 0,
            'GA5ART' => 0,
            'GA6ART' => 0,
            'GA7ART' => 0,
            'GA8ART' => 0,
            'GA9ART' => 0,
            'GA0ART' => 0,
            'IM1ART' => 0,
            'IM2ART' => 0,
            'IM3ART' => 0,
            'IM4ART' => 0,
            'IM5ART' => 0,
            'IM6ART' => 0,
            'IM7ART' => 0,
            'IM8ART' => 0,
            'IM9ART' => 0,
            'IM0ART' => 0,
            'CO1ART' => 0,
            'CO2ART' => 0,
            'CO3ART' => 0,
            'CO4ART' => 0,
            'CO5ART' => 0,
            'CO6ART' => 0,
            'CO7ART' => 0,
            'CO8ART' => 0,
            'CO9ART' => 0,
            'CO0ART' => 0,
            'FechaActualizacionPrecioCosto' => null,
            'AfectarPlanillaTurno' => false,
            'ControlarStock' => false,
            'FechaActualizacionPrecioA' => null,
        ]);

        Arti::create([
            'CODART' => 2,
            'RUBART' => 1,
            'MAAART' => 1,
            'ROBART' => null,
            'PROART' => null,
            'IdImpuestoIva' => 1,
            'DESART' => 'CREDITO TT',
            'CTRART' => null,
            'BARART' => null,
            'IVAART' => 0,
            'UNIART' => null,
            'CANART' => null,
            'ImpuestoInterno' => 0,
            'ITC' => 0,
            'TV' => 0,
            'ITCART' => null,
            'MARART' => 0,
            'MA2ART' => null,
            'MA3ART' => null,
            'PR0ART' => 0,
            'PR1ART' => 0,
            'PR2ART' => 0,
            'PR3ART' => 0,
            'PR4ART' => 0,
            'PR5ART' => 0,
            'PR6ART' => 0,
            'PR7ART' => 0,
            'PR8ART' => 0,
            'ACTART' => 5,
            'MINART' => 5,
            'VTOART' => null,
            'AR1ART' => null,
            'AR2ART' => null,
            'AR3ART' => null,
            'AR4ART' => null,
            'BRUART' => null,
            'PB1ART' => null,
            'PB2ART' => null,
            'PB3ART' => null,
            'CA1ART' => null,
            'CA2ART' => null,
            'CA3ART' => null,
            'CA4ART' => null,
            'GA1ART' => null,
            'GA2ART' => null,
            'GA3ART' => null,
            'GA4ART' => null,
            'GA5ART' => null,
            'GA6ART' => null,
            'GA7ART' => null,
            'GA8ART' => null,
            'GA9ART' => null,
            'GA0ART' => null,
            'IM1ART' => null,
            'IM2ART' => null,
            'IM3ART' => null,
            'IM4ART' => null,
            'IM5ART' => null,
            'IM6ART' => null,
            'IM7ART' => null,
            'IM8ART' => null,
            'IM9ART' => null,
            'IM0ART' => null,
            'CO1ART' => null,
            'CO2ART' => null,
            'CO3ART' => null,
            'CO4ART' => null,
            'CO5ART' => null,
            'CO6ART' => null,
            'CO7ART' => null,
            'CO8ART' => null,
            'CO9ART' => null,
            'CO0ART' => null,
            'FechaActualizacionPrecioCosto' => null,
            'AfectarPlanillaTurno' => false,
            'ControlarStock' => false,
            'FechaActualizacionPrecioA' => null,
        ]);

        Arti::create([
            'CODART' => 3,
            'RUBART' => 1,
            'MAAART' => 1,
            'ROBART' => 0,
            'PROART' => 0,
            'IdImpuestoIva' => 1,
            'DESART' => 'DEBITO TT',
            'CTRART' => null,
            'BARART' => null,
            'IVAART' => 0,
            'UNIART' => null,
            'CANART' => 0.00,
            'ImpuestoInterno' => 0,
            'ITC' => 0,
            'TV' => 0,
            'ITCART' => 0,
            'MARART' => 0,
            'MA2ART' => 0,
            'MA3ART' => 0,
            'PR0ART' => 0,
            'PR1ART' => 0,
            'PR2ART' => 0,
            'PR3ART' => 0,
            'PR4ART' => 0,
            'PR5ART' => 0,
            'PR6ART' => 0,
            'PR7ART' => 0,
            'PR8ART' => 0,
            'ACTART' => 0,
            'MINART' => 0,
            'VTOART' => 0,
            'AR1ART' => 0,
            'AR2ART' => 0,
            'AR3ART' => 0,
            'AR4ART' => 0,
            'BRUART' => 0,
            'PB1ART' => 0,
            'PB2ART' => 0,
            'PB3ART' => 0,
            'CA1ART' => 0,
            'CA2ART' => 0,
            'CA3ART' => 0,
            'CA4ART' => 0,
            'GA1ART' => 0,
            'GA2ART' => 0,
            'GA3ART' => 0,
            'GA4ART' => 0,
            'GA5ART' => 0,
            'GA6ART' => 0,
            'GA7ART' => 0,
            'GA8ART' => 0,
            'GA9ART' => 0,
            'GA0ART' => 0,
            'IM1ART' => 0,
            'IM2ART' => 0,
            'IM3ART' => 0,
            'IM4ART' => 0,
            'IM5ART' => 0,
            'IM6ART' => 0,
            'IM7ART' => 0,
            'IM8ART' => 0,
            'IM9ART' => 0,
            'IM0ART' => 0,
            'CO1ART' => 0,
            'CO2ART' => 0,
            'CO3ART' => 0,
            'CO4ART' => 0,
            'CO5ART' => 0,
            'CO6ART' => 0,
            'CO7ART' => 0,
            'CO8ART' => 0,
            'CO9ART' => 0,
            'CO0ART' => 0,
            'FechaActualizacionPrecioCosto' => null,
            'AfectarPlanillaTurno' => false,
            'ControlarStock' => false,
            'FechaActualizacionPrecioA' => null,
        ]);

        Arti::create([
            'CODART' => 4,
            'RUBART' => 1,
            'MAAART' => 1,
            'ROBART' => 0,
            'PROART' => 0,
            'IdImpuestoIva' => 1,
            'DESART' => 'ARTICULO COMPRA',
            'CTRART' => null,
            'BARART' => null,
            'IVAART' => 0,
            'UNIART' => null,
            'CANART' => 0.00,
            'ImpuestoInterno' => 0,
            'ITC' => 0,
            'TV' => 0,
            'ITCART' => 0,
            'MARART' => 0,
            'MA2ART' => 0,
            'MA3ART' => 0,
            'PR0ART' => 0,
            'PR1ART' => 0,
            'PR2ART' => 0,
            'PR3ART' => 0,
            'PR4ART' => 0,
            'PR5ART' => 0,
            'PR6ART' => 0,
            'PR7ART' => 0,
            'PR8ART' => 0,
            'ACTART' => 0,
            'MINART' => 0,
            'VTOART' => 0,
            'AR1ART' => 0,
            'AR2ART' => 0,
            'AR3ART' => 0,
            'AR4ART' => 0,
            'BRUART' => 0,
            'PB1ART' => 0,
            'PB2ART' => 0,
            'PB3ART' => 0,
            'CA1ART' => 0,
            'CA2ART' => 0,
            'CA3ART' => 0,
            'CA4ART' => 0,
            'GA1ART' => 0,
            'GA2ART' => 0,
            'GA3ART' => 0,
            'GA4ART' => 0,
            'GA5ART' => 0,
            'GA6ART' => 0,
            'GA7ART' => 0,
            'GA8ART' => 0,
            'GA9ART' => 0,
            'GA0ART' => 0,
            'IM1ART' => 0,
            'IM2ART' => 0,
            'IM3ART' => 0,
            'IM4ART' => 0,
            'IM5ART' => 0,
            'IM6ART' => 0,
            'IM7ART' => 0,
            'IM8ART' => 0,
            'IM9ART' => 0,
            'IM0ART' => 0,
            'CO1ART' => 0,
            'CO2ART' => 0,
            'CO3ART' => 0,
            'CO4ART' => 0,
            'CO5ART' => 0,
            'CO6ART' => 0,
            'CO7ART' => 0,
            'CO8ART' => 0,
            'CO9ART' => 0,
            'CO0ART' => 0,
            'FechaActualizacionPrecioCosto' => null,
            'AfectarPlanillaTurno' => false,
            'ControlarStock' => false,
            'FechaActualizacionPrecioA' => null,
        ]);

 ItemFacturaVenta::create([
            'IdFacturaVenta' => 1,
            'ItemNumero' => 1,
            'IdArticulo' => 1,
            'Descripcion' => 'Servicio de mantenimiento',
            'NroDeposito' => 1,
            'Cantidad' => 2,
            'PrecioCosto' => 4000.00,
            'PrecioUnitarioNeto' => 5000.00,
            'PrecioUnitario' => 6050.00,
            'IdImpuestoIva' => 1,
            'AlicuotaIVA' => 21.00,
            'ImpuestoInterno' => 0,
            'ImpuestoCombustible' => 0,
            'ImpuestoTV' => 0,
            'ImpuestosInternos' => 0,
            'Neto' => 10000.00,
            'IVA' => 2100.00,
            'Total' => 12100.00,
            'AfectarPlanillaTurno' => 1,
            'ControlarStock' => 1,
            'Estado' => 'Activo',
            'FechaCreacion' => Carbon::now(),
            'CreadoPor' => 1,
            'FechaActualizacion' => Carbon::now(),
            'ActualizadoPor' => 1,
            'Activo' => 1
        ]);

        $periodos = [
            'Hoy',
            'Últimos 7 días',
            'Últimos 30 días',
            'Últimos 60 días',
            'Últimos 90 días',
            'Primer trimestre',
            'Segundo trimestre',
            'Tercer trimestre',
            'Cuarto trimestre',
        ];

        foreach ($periodos as $index => $nombre) {
            Periodo::create([
                'nombre' => $nombre,
                'orden' => $index + 1
            ]);
        }
    }
}
