INSERT INTO `provincia` (`ID`, `Nombre`) VALUES (1, 'Buenos Aires');
INSERT INTO `provincia` (`ID`, `Nombre`) VALUES (2, 'Capital Federal');
INSERT INTO `provincia` (`ID`, `Nombre`) VALUES (3, 'Catamarca');
INSERT INTO `provincia` (`ID`, `Nombre`) VALUES (4, 'Chaco');
INSERT INTO `provincia` (`ID`, `Nombre`) VALUES (5, 'Chubut');
INSERT INTO `provincia` (`ID`, `Nombre`) VALUES (6, 'Córdoba');
INSERT INTO `provincia` (`ID`, `Nombre`) VALUES (7, 'Corrientes');
INSERT INTO `provincia` (`ID`, `Nombre`) VALUES (8, 'Entre Ríos');
INSERT INTO `provincia` (`ID`, `Nombre`) VALUES (9, 'Formosa');
INSERT INTO `provincia` (`ID`, `Nombre`) VALUES (10, 'Jujuy');
INSERT INTO `provincia` (`ID`, `Nombre`) VALUES (11, 'La Pampa');
INSERT INTO `provincia` (`ID`, `Nombre`) VALUES (12, 'La Rioja');
INSERT INTO `provincia` (`ID`, `Nombre`) VALUES (13, 'Mendoza');
INSERT INTO `provincia` (`ID`, `Nombre`) VALUES (14, 'Misiones');
INSERT INTO `provincia` (`ID`, `Nombre`) VALUES (15, 'Neuquén');
INSERT INTO `provincia` (`ID`, `Nombre`) VALUES (16, 'Río Negro');
INSERT INTO `provincia` (`ID`, `Nombre`) VALUES (17, 'Salta');
INSERT INTO `provincia` (`ID`, `Nombre`) VALUES (18, 'San Juan');
INSERT INTO `provincia` (`ID`, `Nombre`) VALUES (19, 'San Luis');
INSERT INTO `provincia` (`ID`, `Nombre`) VALUES (20, 'Santa Cruz');
INSERT INTO `provincia` (`ID`, `Nombre`) VALUES (21, 'Santa Fe');
INSERT INTO `provincia` (`ID`, `Nombre`) VALUES (22, 'Santiago del Estero');
INSERT INTO `provincia` (`ID`, `Nombre`) VALUES (23, 'Tierra del Fuego');
INSERT INTO `provincia` (`ID`, `Nombre`) VALUES (24, 'Tucumán');
